// Pontes com o português, por palavra (chave = "fr" da palavra no banco).
// Só entra ponte quando a semelhança é real:
//   igual    mesma forma e mesmo sentido;
//   parecida forma quase igual, reconhecível;
//   origem   mesma origem verificável (a nota diz qual);
//   regra    regra de cognato (as palavras com cognate_rule_id ganham a ponte
//            automaticamente no build-seed; aqui só quando a nota precisa ser outra).
// Na dúvida, nada de etimologia: a palavra fica sem ponte e ganha, no máximo,
// uma dica de som no gancho de memória.
//
// Formato: fr: [tipo, português, nota]
export const BRIDGES = {
  // ---- Momento 1: Um café, por favor ----------------------------------------
  bonjour: ['origem', 'bom dia', 'Bon é bom. Jour é dia, parente de jornal e de jornada.'],
  vous: ['origem', 'vós', 'Vem do mesmo latim do nosso vós.'],
  servir: ['igual', 'servir', 'Do verbo servir, igual ao nosso. Je vous sers: eu lhe sirvo.'],
  un: ['parecida', 'um', 'Un é um.'],
  café: ['igual', 'café', 'Igualzinho.'],
  "s'il vous plaît": ['origem', 'se vos apraz', 'Ao pé da letra: se vos apraz, do jeito que se falava no português antigo.'],
  normal: ['igual', 'normal', 'Igual.'],
  ou: ['igual', 'ou', 'Igual.'],
  au: ['parecida', 'ao', 'Au é ao. Café au lait é café ao leite, como chocolate ao leite.'],
  lait: ['origem', 'leite', 'Lait e leite vêm da mesma palavra latina.'],
  et: ['parecida', 'e', 'Et é e. O t fica calado.'],
  croissant: ['igual', 'croissant', 'Essa você já usa.'],
  plaisir: ['parecida', 'prazer', 'Plaisir é prazer. Avec plaisir: com prazer.'],
  merci: ['origem', 'mercê', 'Parente de mercê, de vossa mercê, que virou você.'],
  // Opções do molde do Momento 1
  thé: ['origem', 'chá', 'Thé e chá vêm da mesma palavra chinesa, por caminhos diferentes.'],
  chocolat: ['parecida', 'chocolate', 'Chocolat é chocolate, sem o e do fim.'],

  // ---- Momentos 2 a 13 ------------------------------------------------------
  // igual
  de: ['igual', 'de', 'Igual.'],
  euro: ['igual', 'euro', 'Igual.'],
  onze: ['igual', 'onze', 'Igual, até no som.'],
  dormir: ['igual', 'dormir', 'Igual.'],
  super: ['igual', 'super', 'Igual ao nosso super, de muito bom.'],
  grave: ['igual', 'grave', 'Igual: ce n’est pas grave, não é grave.'],
  // parecida
  à: ['parecida', 'a', 'À é a, como em à gauche, à esquerda.'],
  une: ['parecida', 'uma', 'Une é uma.'],
  tu: ['parecida', 'tu', 'O nosso tu, que no francês é o você de quem é próximo.'],
  elle: ['parecida', 'ela', 'Elle é ela.'],
  non: ['parecida', 'não', 'Non é não.'],
  bon: ['parecida', 'bom', 'Bon é bom.'],
  bonne: ['parecida', 'boa', 'Bonne é boa, o feminino de bon.'],
  bien: ['parecida', 'bem', 'Bien é bem.'],
  trois: ['parecida', 'três', 'Trois é três.'],
  douze: ['parecida', 'doze', 'Douze é doze.'],
  neuf: ['parecida', 'nove', 'Neuf é nove (e também novo).'],
  quel: ['parecida', 'qual', 'Quel é qual.'],
  numéro: ['parecida', 'número', 'Numéro é número.'],
  moment: ['parecida', 'momento', 'Moment é momento, sem o o do fim.'],
  "d'accord": ['parecida', 'de acordo', "D'accord é de acordo: combinado."],
  pardon: ['parecida', 'perdão', 'Pardon é perdão: desculpe.'],
  madame: ['parecida', 'madame', 'Madame também existe no português: é a senhora.'],
  rue: ['parecida', 'rua', 'Rue é rua.'],
  famille: ['parecida', 'família', 'Famille é família.'],
  fièvre: ['parecida', 'febre', 'Fièvre é febre.'],
  français: ['parecida', 'francês', 'Français é francês: o -ês vira -ais, como em portugais.'],
  apprendre: ['parecida', 'aprender', 'Apprendre é aprender.'],
  parfait: ['parecida', 'perfeito', 'Parfait é perfeito.'],
  passeport: ['parecida', 'passaporte', 'Passeport é passaporte.'],
  contrat: ['parecida', 'contrato', 'Contrat é contrato.'],
  ticket: ['parecida', 'tíquete', 'Ticket é o tíquete, a senha.'],
  timide: ['parecida', 'tímido', 'Timide é tímido.'],
  répéter: ['parecida', 'repetir', 'Répéter é repetir.'],
  bienvenue: ['parecida', 'bem-vindo', 'Bien é bem, venue é vinda: bem-vindo.'],
  chèque: ['parecida', 'cheque', 'Chèque é cheque.'],
  heure: ['parecida', 'hora', 'Heure é hora; o h não soa.'],
  // origem (justificativa em ORIGIN_NOTES)
  la: ['origem', 'a', 'La e o nosso a vêm da mesma palavra latina, illa.'],
  le: ['origem', 'o', 'Le e o nosso o vêm da mesma palavra latina, ille.'],
  les: ['origem', 'os, as', 'Les e os nossos os e as vêm do mesmo latim, illos e illas.'],
  venir: ['origem', 'vir', 'Venir e vir vêm do latim venire.'],
  parler: ['origem', 'parlamento', 'Parler é falar: o parlamento é o lugar onde se fala.'],
  peu: ['origem', 'pouco', 'Peu e pouco vêm do latim paucum.'],
  mais: ['origem', 'mas', 'Mais e mas vêm do latim magis.'],
  jour: ['origem', 'dia', 'Jour é dia, parente de jornal e de jornada.'],
  pour: ['origem', 'por', 'Pour vem do latim pro, o mesmo do nosso por.'],
  pouvoir: ['origem', 'poder', 'Pouvoir e poder vêm do latim potere.'],
  plus: ['origem', 'mais', 'Plus é mais, do latim plus, o mesmo de plural.'],
  manger: ['origem', 'manjar', 'Manger é comer; vem do latim manducare, que deu o nosso manjar.'],
  devoir: ['origem', 'dever', 'Devoir e dever vêm do latim debere.'],
  payer: ['origem', 'pagar', 'Payer e pagar vêm do latim pacare.'],
  par: ['origem', 'por', 'Par vem do latim per: por.'],
  carte: ['origem', 'cartão', 'Carte vem do latim charta, a mesma origem de carta e cartão.'],
  tout: ['origem', 'todo', 'Tout e todo vêm do latim totus.'],
  avoir: ['origem', 'haver', 'Avoir e o nosso haver vêm do latim habere: eu hei de, j’ai.'],
  prendre: ['origem', 'prender', 'Prendre vem do latim prehendere, como prender: pegar.'],
  votre: ['origem', 'vosso', 'Votre e vosso vêm do latim voster.'],
  vouloir: ['origem', 'vontade', 'Vouloir é querer, da mesma raiz de vontade e voluntário.'],
  travailler: ['origem', 'trabalhar', 'Travailler e trabalhar vêm da mesma palavra do latim tardio.'],
  travail: ['origem', 'trabalho', 'Travail e trabalho têm a mesma origem.'],
  enfant: ['origem', 'infantil', 'Enfant vem do latim infans, como infantil e infância.'],
  jouer: ['origem', 'jogar', 'Jouer vem do latim jocari, parente de jogo: brincar, jogar.'],
  demain: ['origem', 'amanhã', 'Demain e amanhã vêm do latim de mane, de manhã.'],
  faire: ['origem', 'fazer', 'Faire e fazer vêm do latim facere.'],
  repas: ['origem', 'repasto', 'Repas é refeição, da mesma origem de repasto.'],
  poisson: ['origem', 'peixe', 'Poisson vem do latim piscis, como piscicultura.'],
  aimer: ['origem', 'amar', 'Aimer e amar vêm do latim amare.'],
  nouveau: ['origem', 'novo', 'Nouveau e novo vêm do latim novus.'],
  // ---- Momentos 14 a 21 ------------------------------------------------------
  classe: ['igual', 'classe', 'Igual: première classe, primeira classe.'],
  sept: ['parecida', 'sete', 'Sept é sete; o p não soa.'],
  deux: ['parecida', 'dois', 'Deux é dois.'],
  dix: ['parecida', 'dez', 'Dix é dez.'],
  vingt: ['parecida', 'vinte', 'Vingt é vinte; só o som nasal fica.'],
  minute: ['parecida', 'minuto', 'Minute é minuto.'],
  rapide: ['parecida', 'rápido', 'Rapide é rápido.'],
  il: ['parecida', 'ele', 'Il é ele.'],
  nous: ['parecida', 'nós', 'Nous é nós.'],
  en: ['parecida', 'em', 'En é em.'],
  ami: ['parecida', 'amigo', 'Ami é amigo.'],
  train: ['parecida', 'trem', 'Train é trem.'],
  gratuit: ['parecida', 'gratuito', 'Gratuit é gratuito.'],
  sac: ['parecida', 'saco', 'Sac é saco, a sacola.'],
  entrée: ['parecida', 'entrada', 'Entrée é entrada.'],
  fromage: ['origem', 'forma', 'Fromage vem de formaticum, o queijo feito na forma.'],
  bus: ['origem', 'ônibus', 'Bus é o fim de omnibus, a mesma palavra do nosso ônibus.'],
  retard: ['origem', 'retardar', 'Retard é atraso, da família de retardar.'],
  chez: ['origem', 'casa', 'Chez vem do latim casa, a mesma palavra do nosso casa: chez moi, na minha casa.'],
  travaux: ['origem', 'trabalhos', 'Travaux, as obras, é o plural de travail, trabalho.'],
  regarder: ['origem', 'guardar', 'Regarder é olhar: re + garder, da mesma origem de guardar.'],
  sauf: ['origem', 'salvo', 'Sauf é salvo, no sentido de exceto: salvo na primeira classe.'],
  pain: ['origem', 'pão', 'Pain e pão vêm do latim panem.'],
  vin: ['origem', 'vinho', 'Vin e vinho vêm do latim vinum.'],
  matin: ['origem', 'matinal', 'Matin é manhã, da mesma raiz de matinal e matutino.'],
  fond: ['origem', 'fundo', 'Fond e fundo vêm do latim fundus: au fond, no fundo.'],
  droite: ['origem', 'direita', 'Droite e direita vêm do latim directus.'],
  bouteille: ['origem', 'botelha', 'Bouteille é garrafa, da mesma origem de botelha e botija.'],
  même: ['origem', 'mesmo', 'Même e mesmo vêm do mesmo latim, metipsimus.'],
  donner: ['origem', 'doar', 'Donner é dar, do latim donare, como doar e doação.'],
  caisse: ['origem', 'caixa', 'Caisse e caixa vêm do latim capsa.'],
  magasin: ['origem', 'armazém', 'Magasin é loja; vem do árabe makhzan, o mesmo do nosso armazém.'],
  // ---- Momentos 22 a 29 ------------------------------------------------------
  quinze: ['igual', 'quinze', 'Igual.'],
  paracétamol: ['igual', 'paracetamol', 'Igual.'],
  pédiatre: ['parecida', 'pediatra', 'Pédiatre é pediatra.'],
  cabinet: ['parecida', 'gabinete', 'Cabinet é o consultório, a mesma palavra do nosso gabinete.'],
  médicament: ['parecida', 'medicamento', 'Médicament é medicamento, o remédio.'],
  envoyer: ['parecida', 'enviar', 'Envoyer é enviar.'],
  dossier: ['parecida', 'dossiê', 'Dossier é o dossiê: a pasta com os seus papéis.'],
  comprendre: ['parecida', 'compreender', 'Comprendre é compreender, entender.'],
  document: ['parecida', 'documento', 'Document é documento.'],
  date: ['parecida', 'data', 'Date é data.'],
  quand: ['parecida', 'quando', 'Quand é quando.'],
  tousser: ['parecida', 'tossir', 'Tousser é tossir.'],
  montant: ['parecida', 'montante', 'Montant é o montante, o valor.'],
  quatre: ['parecida', 'quatro', 'Quatre é quatro.'],
  détail: ['parecida', 'detalhe', 'Détail é detalhe.'],
  brésilien: ['parecida', 'brasileiro', 'Brésilien é brasileiro.'],
  âge: ['origem', 'idade', 'Âge e idade vêm do mesmo latim, aetas: quel âge, que idade.'],
  an: ['origem', 'ano', 'An e ano vêm do latim annus.'],
  fille: ['origem', 'filha', 'Fille e filha vêm do latim filia.'],
  place: ['origem', 'praça', 'Place é lugar ou vaga, e também praça: as duas vêm do latim platea.'],
  rembourser: ['origem', 'reembolsar', 'Rembourser é reembolsar: pôr de volta na bourse, a bolsa.'],
  remboursement: ['origem', 'reembolso', 'Remboursement é o reembolso, de bourse, bolsa.'],
  reçu: ['origem', 'recebido', 'Reçu é o recibo, de recevoir, receber.'],
  sirop: ['origem', 'xarope', 'Sirop e xarope vêm da mesma palavra árabe, sharab.'],
  eau: ['origem', 'água', 'Eau e água vêm do latim aqua; o caminho até o francês encurtou tudo em ô.'],
  compte: ['origem', 'conta', 'Compte e conta vêm do latim computus, de contar.'],
  semaine: ['origem', 'semana', 'Semaine e semana vêm do latim septimana.'],
  prix: ['origem', 'preço', 'Prix e preço vêm do latim pretium.'],
  mois: ['origem', 'mês', 'Mois e mês vêm do latim mensis.'],
  sécurité: ['origem', 'segurança', 'Sécurité vem do latim securitas, como segurança e seguridade.'],
  douleur: ['origem', 'dor', 'Douleur e dor vêm do latim dolor.'],
  tête: ['origem', 'testa', 'Tête vem do latim testa: o s caiu e deixou o acento circunflexo.'],
  ordonnance: ['origem', 'ordem', 'Ordonnance é a receita: a ordem escrita do médico, de ordonner, ordenar.'],
  soixante: ['origem', 'sessenta', 'Soixante e sessenta vêm do latim sexaginta.'],
  // ---- Momentos 30 a 37 ------------------------------------------------------
  partir: ['igual', 'partir', 'Igual: partir, ir embora.'],
  équipe: ['igual', 'equipe', 'Igual: équipe é equipe.'],
  que: ['igual', 'que', 'Igual.'],
  anglais: ['parecida', 'inglês', 'Anglais é inglês: o -ês vira -ais.'],
  réunion: ['parecida', 'reunião', 'Réunion é reunião.'],
  plante: ['parecida', 'planta', 'Plante é planta.'],
  "bon voyage": ['parecida', 'boa viagem', 'Bon voyage é boa viagem.'],
  collègue: ['parecida', 'colega', 'Collègue é colega.'],
  papier: ['parecida', 'papel', 'Papier é papel.'],
  cinq: ['parecida', 'cinco', 'Cinq é cinco.'],
  client: ['parecida', 'cliente', 'Client é cliente.'],
  important: ['parecida', 'importante', 'Important é importante.'],
  intéressant: ['parecida', 'interessante', 'Intéressant é interessante.'],
  conteneur: ['parecida', 'contêiner', 'Conteneur é o contêiner.'],
  raison: ['origem', 'razão', 'Raison e razão vêm do latim ratio.'],
  soir: ['origem', 'serão', 'Soir é a noite, o fim do dia; vem do latim sero, tarde, o mesmo do nosso serão.'],
  soirée: ['origem', 'serão', 'Soirée é a noite toda, a mesma raiz de soir e do nosso serão.'],
  bonsoir: ['origem', 'boa noite', 'Bon é bom, soir é a noite: bonsoir, boa noite ao chegar.'],
  garder: ['origem', 'guardar', 'Garder e guardar vêm da mesma palavra germânica.'],
  clé: ['origem', 'clave', 'Clé vem do latim clavis, como clave, a chave da música.'],
  courrier: ['origem', 'correio', 'Courrier e correio vêm do latim currere, correr: quem leva a carta corre.'],
  dire: ['origem', 'dizer', 'Dire e dizer vêm do latim dicere.'],
  personne: ['origem', 'pessoa', 'Personne e pessoa vêm do latim persona.'],
  mettre: ['origem', 'meter', 'Mettre é pôr, do latim mittere, que deu meter.'],
  verre: ['origem', 'vidro', 'Verre e vidro vêm do latim vitrum.'],
  voisine: ['origem', 'vizinha', 'Voisine e vizinha vêm do latim vicinus.'],
  voisin: ['origem', 'vizinho', 'Voisin e vizinho vêm do latim vicinus.'],
  immeuble: ['origem', 'imóvel', 'Immeuble é o prédio, o imóvel: o que não se move.'],
  langue: ['origem', 'língua', 'Langue e língua vêm do latim lingua.'],
  commencer: ['origem', 'começar', 'Commencer e começar vêm do latim vulgar cominitiare.'],
};

/**
 * Justificativa das pontes do tipo "origem" (vai para o relatório de conteúdo).
 * Só origens de dicionário etimológico, sem suposição.
 */
export const ORIGIN_NOTES = {
  bonjour: 'jour vem do latim diurnum (do dia); jornal e jornada vêm de diurnalis/diurnata, da mesma raiz. bon e bom vêm de bonus.',
  vous: 'francês vous e português vós vêm ambos do pronome latino vos.',
  "s'il vous plaît": 'plaire vem do latim placere; o português aprazer vem de ad + placere. "Se vos apraz" é a tradução literal.',
  lait: 'francês lait e português leite vêm do latim lac, lactis (acusativo lactem).',
  thé: 'o mesmo caractere chinês 茶: "chá" veio da pronúncia de Cantão (via Macau), "thé" da pronúncia de Fujian "te" (via Holanda).',
  la: 'artigo definido do latim illa (demonstrativo): francês la; português antigo la/a.',
  le: 'francês le e português o (antigo lo) vêm do demonstrativo latino ille/illum.',
  les: 'plural do mesmo demonstrativo latino (illos/illas), que deu os/as em português.',
  venir: 'francês venir e português vir vêm do latim venire.',
  parler: 'parlement (parlamento) deriva de parler; parler vem do latim parabolare.',
  peu: 'francês peu e português pouco vêm do latim paucum.',
  mais: 'francês mais e português mas vêm do latim magis.',
  jour: 'jour vem do latim diurnum; jornal e jornada vêm de diurnalis/diurnata, da mesma raiz.',
  pour: 'francês pour vem do latim pro (via por/pur no francês antigo); português por vem de pro.',
  pouvoir: 'francês pouvoir e português poder vêm do latim vulgar potere.',
  plus: 'francês plus é o latim plus; plural vem de pluralis, da mesma raiz.',
  manger: 'francês manger vem do latim manducare; português manjar vem do francês antigo mangier, da mesma origem.',
  devoir: 'francês devoir e português dever vêm do latim debere.',
  payer: 'francês payer e português pagar vêm do latim pacare.',
  par: 'francês par vem do latim per, que deu per/por em português.',
  carte: 'francês carte vem do latim charta, que deu carta; cartão vem do italiano cartone, da mesma raiz.',
  tout: 'francês tout e português todo vêm do latim totus.',
  avoir: 'francês avoir e português haver vêm do latim habere.',
  prendre: 'francês prendre e português prender vêm do latim prehendere.',
  votre: 'francês votre e português vosso vêm do latim vulgar voster.',
  vouloir: 'francês vouloir vem do latim vulgar volere; vontade vem de voluntas e voluntário de voluntarius, da mesma raiz.',
  travailler: 'francês travailler e português trabalhar vêm do latim tardio tripaliare.',
  travail: 'francês travail e português trabalho vêm do latim tardio tripalium.',
  enfant: 'francês enfant vem do latim infans, que deu infante, infantil e infância.',
  jouer: 'francês jouer vem do latim jocari, derivado de jocus, que deu jogo.',
  demain: 'francês demain e português amanhã vêm do latim de mane (de manhã).',
  faire: 'francês faire e português fazer vêm do latim facere.',
  repas: 'francês repas vem de re + past (latim pastus), a mesma origem de repasto.',
  poisson: 'francês poisson vem do latim piscis, que deu peixe e piscicultura.',
  aimer: 'francês aimer e português amar vêm do latim amare.',
  nouveau: 'francês nouveau e português novo vêm do latim novus.',
  fromage: 'fromage vem do latim vulgar formaticus (caseus formaticus, queijo feito em forma).',
  bus: 'bus é a forma curta de omnibus (latim: para todos), que em português deu ônibus.',
  retard: 'retard deriva de retarder, do latim retardare, que deu retardar.',
  chez: 'chez vem do latim casa (em casa de); o português casa vem da mesma palavra.',
  travaux: 'travaux é o plural de travail, do latim tardio tripalium, que deu trabalho.',
  regarder: 're- + garder; garder vem do germânico wardon, que deu guardar em português.',
  sauf: 'sauf vem do latim salvus, que deu salvo (e salvo = exceto).',
  pain: 'pain e pão vêm do latim panem.',
  vin: 'vin e vinho vêm do latim vinum.',
  matin: 'matin vem do latim matutinum, que deu matutino e matinal.',
  fond: 'fond e fundo vêm do latim fundus.',
  droite: 'droite e direita vêm do latim directus.',
  bouteille: 'bouteille vem do latim tardio butticula; botelha vem do francês antigo, da mesma origem.',
  même: 'même e mesmo vêm do latim vulgar metipsimus.',
  donner: 'donner vem do latim donare, que deu doar.',
  caisse: 'caisse vem do provençal caissa, do latim capsa, que deu caixa.',
  magasin: 'magasin vem do árabe makhāzin (depósitos); armazém vem do árabe al-makhzan.',
  âge: 'âge vem do latim vulgar aetaticum, de aetas; idade vem de aetatem.',
  an: 'an e ano vêm do latim annus.',
  fille: 'fille e filha vêm do latim filia.',
  place: 'place e praça vêm do latim platea.',
  rembourser: 're- + en- + bourse (bolsa, do latim bursa); o português reembolsar tem a mesma formação com bolso/bolsa.',
  remboursement: 'derivado de rembourser (ver acima).',
  reçu: 'reçu é o particípio de recevoir, do latim recipere, que deu receber.',
  sirop: 'sirop vem do latim medieval sirupus, do árabe sharāb; xarope vem do árabe sharāb.',
  eau: 'eau vem do latim aqua (francês antigo eve, ewe); água vem de aqua.',
  compte: 'compte vem do latim computus; conta vem de computare.',
  semaine: 'semaine e semana vêm do latim septimana.',
  prix: 'prix e preço vêm do latim pretium.',
  mois: 'mois e mês vêm do latim mensis.',
  sécurité: 'sécurité vem do latim securitas; segurança e seguridade vêm de securus, da mesma raiz.',
  douleur: 'douleur e dor vêm do latim dolor (acusativo dolorem).',
  tête: 'tête vem do latim testa (francês antigo teste); testa em português vem da mesma palavra.',
  ordonnance: 'ordonnance deriva de ordonner, do latim ordinare, que deu ordenar e ordem.',
  soixante: 'soixante e sessenta vêm do latim sexaginta.',
  raison: 'raison e razão vêm do latim ratio (acusativo rationem).',
  soir: 'soir vem do latim sero (tarde); serão vem do latim serum/serotinus, da mesma raiz.',
  soirée: 'soirée deriva de soir (ver acima).',
  bonsoir: 'bon (latim bonus) + soir (latim sero).',
  garder: 'garder vem do franco wardon; guardar vem do germânico wardon, a mesma palavra.',
  clé: 'clé vem do latim clavis, que deu clave (e chave, por outra via).',
  courrier: 'courrier vem do italiano corriere; correio vem do catalão/provençal; ambos derivam do latim currere.',
  dire: 'dire e dizer vêm do latim dicere.',
  personne: 'personne e pessoa vêm do latim persona.',
  mettre: 'mettre e meter vêm do latim mittere.',
  verre: 'verre e vidro vêm do latim vitrum.',
  voisine: 'voisin(e) e vizinho(a) vêm do latim vicinus.',
  voisin: 'voisin e vizinho vêm do latim vicinus.',
  immeuble: 'immeuble vem do latim immobilis (que não se move), que deu imóvel.',
  langue: 'langue e língua vêm do latim lingua.',
  commencer: 'commencer e começar vêm do latim vulgar cominitiare.',
  merci: 'merci vem do latim mercedem (recompensa, graça), o mesmo de mercê; "vossa mercê" deu "você".',
};
