// Pontes com o português, por palavra (chave = "fr" da palavra no banco).
// Só entra ponte quando a semelhança é real:
//   igual    mesma forma e mesmo sentido;
//   parecida forma quase igual, reconhecível;
//   origem   mesma origem verificável (a nota diz qual);
//   regra    regra de cognato (as palavras com cognate_rule_id ganham a ponte
//            automaticamente no build-seed; aqui só quando a nota precisa ser outra).
// Na dúvida, nada de etimologia: a palavra fica sem ponte e ganha, no máximo,
// uma dica de som no gancho de memória.
//
// Formato: fr: [tipo, português, nota]
export const BRIDGES = {
  // ---- Momento 1: Um café, por favor ----------------------------------------
  bonjour: ['origem', 'bom dia', 'Bon é bom. Jour é dia, parente de jornal e de jornada.'],
  vous: ['origem', 'vós', 'Vem do mesmo latim do nosso vós.'],
  servir: ['igual', 'servir', 'Do verbo servir, igual ao nosso. Je vous sers: eu lhe sirvo.'],
  un: ['parecida', 'um', 'Un é um.'],
  café: ['igual', 'café', 'Igualzinho.'],
  "s'il vous plaît": ['origem', 'se vos apraz', 'Ao pé da letra: se vos apraz, do jeito que se falava no português antigo.'],
  normal: ['igual', 'normal', 'Igual.'],
  ou: ['igual', 'ou', 'Igual.'],
  au: ['parecida', 'ao', 'Au é ao. Café au lait é café ao leite, como chocolate ao leite.'],
  lait: ['origem', 'leite', 'Lait e leite vêm da mesma palavra latina.'],
  et: ['parecida', 'e', 'Et é e. O t fica calado.'],
  croissant: ['igual', 'croissant', 'Essa você já usa.'],
  plaisir: ['parecida', 'prazer', 'Plaisir é prazer. Avec plaisir: com prazer.'],
  merci: ['origem', 'mercê', 'Parente de mercê, de vossa mercê, que virou você.'],
  // Opções do molde do Momento 1
  thé: ['origem', 'chá', 'Thé e chá vêm da mesma palavra chinesa, por caminhos diferentes.'],
  chocolat: ['parecida', 'chocolate', 'Chocolat é chocolate, sem o e do fim.'],

  // ---- Momentos 2 a 13 ------------------------------------------------------
  // igual
  de: ['igual', 'de', 'Igual.'],
  euro: ['igual', 'euro', 'Igual.'],
  onze: ['igual', 'onze', 'Igual, até no som.'],
  dormir: ['igual', 'dormir', 'Igual.'],
  super: ['igual', 'super', 'Igual ao nosso super, de muito bom.'],
  grave: ['igual', 'grave', 'Igual: ce n’est pas grave, não é grave.'],
  // parecida
  à: ['parecida', 'a', 'À é a, como em à gauche, à esquerda.'],
  une: ['parecida', 'uma', 'Une é uma.'],
  tu: ['parecida', 'tu', 'O nosso tu, que no francês é o você de quem é próximo.'],
  elle: ['parecida', 'ela', 'Elle é ela.'],
  non: ['parecida', 'não', 'Non é não.'],
  bon: ['parecida', 'bom', 'Bon é bom.'],
  bonne: ['parecida', 'boa', 'Bonne é boa, o feminino de bon.'],
  bien: ['parecida', 'bem', 'Bien é bem.'],
  trois: ['parecida', 'três', 'Trois é três.'],
  douze: ['parecida', 'doze', 'Douze é doze.'],
  neuf: ['parecida', 'nove', 'Neuf é nove (e também novo).'],
  quel: ['parecida', 'qual', 'Quel é qual.'],
  numéro: ['parecida', 'número', 'Numéro é número.'],
  moment: ['parecida', 'momento', 'Moment é momento, sem o o do fim.'],
  "d'accord": ['parecida', 'de acordo', "D'accord é de acordo: combinado."],
  pardon: ['parecida', 'perdão', 'Pardon é perdão: desculpe.'],
  madame: ['parecida', 'madame', 'Madame também existe no português: é a senhora.'],
  rue: ['parecida', 'rua', 'Rue é rua.'],
  famille: ['parecida', 'família', 'Famille é família.'],
  fièvre: ['parecida', 'febre', 'Fièvre é febre.'],
  français: ['parecida', 'francês', 'Français é francês: o -ês vira -ais, como em portugais.'],
  apprendre: ['parecida', 'aprender', 'Apprendre é aprender.'],
  parfait: ['parecida', 'perfeito', 'Parfait é perfeito.'],
  passeport: ['parecida', 'passaporte', 'Passeport é passaporte.'],
  contrat: ['parecida', 'contrato', 'Contrat é contrato.'],
  ticket: ['parecida', 'tíquete', 'Ticket é o tíquete, a senha.'],
  timide: ['parecida', 'tímido', 'Timide é tímido.'],
  répéter: ['parecida', 'repetir', 'Répéter é repetir.'],
  bienvenue: ['parecida', 'bem-vindo', 'Bien é bem, venue é vinda: bem-vindo.'],
  chèque: ['parecida', 'cheque', 'Chèque é cheque.'],
  heure: ['parecida', 'hora', 'Heure é hora; o h não soa.'],
  // origem (justificativa em ORIGIN_NOTES)
  la: ['origem', 'a', 'La e o nosso a vêm da mesma palavra latina, illa.'],
  le: ['origem', 'o', 'Le e o nosso o vêm da mesma palavra latina, ille.'],
  les: ['origem', 'os, as', 'Les e os nossos os e as vêm do mesmo latim, illos e illas.'],
  venir: ['origem', 'vir', 'Venir e vir vêm do latim venire.'],
  parler: ['origem', 'parlamento', 'Parler é falar: o parlamento é o lugar onde se fala.'],
  peu: ['origem', 'pouco', 'Peu e pouco vêm do latim paucum.'],
  mais: ['origem', 'mas', 'Mais e mas vêm do latim magis.'],
  jour: ['origem', 'dia', 'Jour é dia, parente de jornal e de jornada.'],
  pour: ['origem', 'por', 'Pour vem do latim pro, o mesmo do nosso por.'],
  pouvoir: ['origem', 'poder', 'Pouvoir e poder vêm do latim potere.'],
  plus: ['origem', 'mais', 'Plus é mais, do latim plus, o mesmo de plural.'],
  manger: ['origem', 'manjar', 'Manger é comer; vem do latim manducare, que deu o nosso manjar.'],
  devoir: ['origem', 'dever', 'Devoir e dever vêm do latim debere.'],
  payer: ['origem', 'pagar', 'Payer e pagar vêm do latim pacare.'],
  par: ['origem', 'por', 'Par vem do latim per: por.'],
  carte: ['origem', 'cartão', 'Carte vem do latim charta, a mesma origem de carta e cartão.'],
  tout: ['origem', 'todo', 'Tout e todo vêm do latim totus.'],
  avoir: ['origem', 'haver', 'Avoir e o nosso haver vêm do latim habere: eu hei de, j’ai.'],
  prendre: ['origem', 'prender', 'Prendre vem do latim prehendere, como prender: pegar.'],
  votre: ['origem', 'vosso', 'Votre e vosso vêm do latim voster.'],
  vouloir: ['origem', 'vontade', 'Vouloir é querer, da mesma raiz de vontade e voluntário.'],
  travailler: ['origem', 'trabalhar', 'Travailler e trabalhar vêm da mesma palavra do latim tardio.'],
  travail: ['origem', 'trabalho', 'Travail e trabalho têm a mesma origem.'],
  enfant: ['origem', 'infantil', 'Enfant vem do latim infans, como infantil e infância.'],
  jouer: ['origem', 'jogar', 'Jouer vem do latim jocari, parente de jogo: brincar, jogar.'],
  demain: ['origem', 'amanhã', 'Demain e amanhã vêm do latim de mane, de manhã.'],
  faire: ['origem', 'fazer', 'Faire e fazer vêm do latim facere.'],
  repas: ['origem', 'repasto', 'Repas é refeição, da mesma origem de repasto.'],
  poisson: ['origem', 'peixe', 'Poisson vem do latim piscis, como piscicultura.'],
  aimer: ['origem', 'amar', 'Aimer e amar vêm do latim amare.'],
  nouveau: ['origem', 'novo', 'Nouveau e novo vêm do latim novus.'],
};

/**
 * Justificativa das pontes do tipo "origem" (vai para o relatório de conteúdo).
 * Só origens de dicionário etimológico, sem suposição.
 */
export const ORIGIN_NOTES = {
  bonjour: 'jour vem do latim diurnum (do dia); jornal e jornada vêm de diurnalis/diurnata, da mesma raiz. bon e bom vêm de bonus.',
  vous: 'francês vous e português vós vêm ambos do pronome latino vos.',
  "s'il vous plaît": 'plaire vem do latim placere; o português aprazer vem de ad + placere. "Se vos apraz" é a tradução literal.',
  lait: 'francês lait e português leite vêm do latim lac, lactis (acusativo lactem).',
  thé: 'o mesmo caractere chinês 茶: "chá" veio da pronúncia de Cantão (via Macau), "thé" da pronúncia de Fujian "te" (via Holanda).',
  la: 'artigo definido do latim illa (demonstrativo): francês la; português antigo la/a.',
  le: 'francês le e português o (antigo lo) vêm do demonstrativo latino ille/illum.',
  les: 'plural do mesmo demonstrativo latino (illos/illas), que deu os/as em português.',
  venir: 'francês venir e português vir vêm do latim venire.',
  parler: 'parlement (parlamento) deriva de parler; parler vem do latim parabolare.',
  peu: 'francês peu e português pouco vêm do latim paucum.',
  mais: 'francês mais e português mas vêm do latim magis.',
  jour: 'jour vem do latim diurnum; jornal e jornada vêm de diurnalis/diurnata, da mesma raiz.',
  pour: 'francês pour vem do latim pro (via por/pur no francês antigo); português por vem de pro.',
  pouvoir: 'francês pouvoir e português poder vêm do latim vulgar potere.',
  plus: 'francês plus é o latim plus; plural vem de pluralis, da mesma raiz.',
  manger: 'francês manger vem do latim manducare; português manjar vem do francês antigo mangier, da mesma origem.',
  devoir: 'francês devoir e português dever vêm do latim debere.',
  payer: 'francês payer e português pagar vêm do latim pacare.',
  par: 'francês par vem do latim per, que deu per/por em português.',
  carte: 'francês carte vem do latim charta, que deu carta; cartão vem do italiano cartone, da mesma raiz.',
  tout: 'francês tout e português todo vêm do latim totus.',
  avoir: 'francês avoir e português haver vêm do latim habere.',
  prendre: 'francês prendre e português prender vêm do latim prehendere.',
  votre: 'francês votre e português vosso vêm do latim vulgar voster.',
  vouloir: 'francês vouloir vem do latim vulgar volere; vontade vem de voluntas e voluntário de voluntarius, da mesma raiz.',
  travailler: 'francês travailler e português trabalhar vêm do latim tardio tripaliare.',
  travail: 'francês travail e português trabalho vêm do latim tardio tripalium.',
  enfant: 'francês enfant vem do latim infans, que deu infante, infantil e infância.',
  jouer: 'francês jouer vem do latim jocari, derivado de jocus, que deu jogo.',
  demain: 'francês demain e português amanhã vêm do latim de mane (de manhã).',
  faire: 'francês faire e português fazer vêm do latim facere.',
  repas: 'francês repas vem de re + past (latim pastus), a mesma origem de repasto.',
  poisson: 'francês poisson vem do latim piscis, que deu peixe e piscicultura.',
  aimer: 'francês aimer e português amar vêm do latim amare.',
  nouveau: 'francês nouveau e português novo vêm do latim novus.',
  merci: 'merci vem do latim mercedem (recompensa, graça), o mesmo de mercê; "vossa mercê" deu "você".',
};
