// A trilha: capítulos na ordem da vida de quem chega e, em cada um, os Momentos.
//
// Cada Momento é uma cena curta da vida real em Luxemburgo, com um arco fixo:
// escutar → ver o que já sabe → uma chave → montar → falar → levar consigo.
//
// Falas: [quem fala, francês marcado, português]. No francês, cada palavra do
// banco vai entre colchetes: [texto] ou [texto|palavra do banco] ou
// [texto|palavra do banco|tradução desta forma]. Tudo fora dos colchetes é
// pontuação ou nome próprio. O build-seed confere que toda palavra existe e
// calcula word_ids; a tipografia francesa (espaço fino antes de ! ? : ;) é
// aplicada no build.
//
// Par mínimo (opcional): pair: 'rue/roue', com uma das palavras no diálogo;
// pronoun ('Ela' ou 'Ele') é quem fala com você, para a pergunta do passo 1.
//
// Chave: exemplos com a parte em destaque entre colchetes ("vou[s]"), sempre
// tirados do diálogo. apply: palavras novas para prever e depois ouvir.

export const CHAPTERS = [
  { id: 'ch1', title: 'Primeiros passos', scene: 'sc_cotidiano' },
  { id: 'ch2', title: 'A Commune', scene: 'sc_lu_commune' },
  { id: 'ch3', title: 'Creche e CSA', scene: 'sc_lu_creche' },
  { id: 'ch4', title: 'Supermercado', scene: 'sc_lu_mercado' },
  { id: 'ch5', title: 'Transporte', scene: 'sc_lu_transporte' },
  { id: 'ch6', title: 'Médico e farmácia', scene: 'sc_lu_pediatra' },
  { id: 'ch7', title: 'Banco', scene: 'sc_lu_banco' },
  { id: 'ch8', title: 'Vizinhança', scene: 'sc_lu_vizinhanca' },
  { id: 'ch9', title: 'Entrevista de emprego', scene: 'sc_lu_entrevista' },
];

export const MOMENTOS = [
  // ===========================================================================
  // Capítulo 1 · Primeiros passos
  // ===========================================================================
  {
    id: 'm01', chapter: 'ch1',
    title: 'Um café, por favor',
    can_do: 'pedir algo num café',
    intro: 'Primeira manhã em Luxemburgo. Você entra no café da esquina e a atendente fala com você.',
    lines: [
      ['Atendente', "[Bonjour] ! [Qu'est-ce que] [je] [vous] [sers|servir|sirvo] ?", 'Bom dia! O que eu lhe sirvo?'],
      ['Você', "[Bonjour]. [Un] [café], [s'il vous plaît].", 'Bom dia. Um café, por favor.'],
      ['Atendente', '[Un] [café] [normal] [ou] [un] [café] [au] [lait] ?', 'Um café normal ou um café com leite?'],
      ['Você', "[Au] [lait]. [Et] [un] [croissant], [s'il vous plaît].", 'Com leite. E um croissant, por favor.'],
      ['Atendente', '[Avec] [plaisir].', 'Com prazer.'],
      ['Você', '[Merci] !', 'Obrigado!'],
    ],
    key: {
      kind: 'leitura', ref: 'rr_final_cons', name: 'letras caladas', chapter: 2,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['vou[s]', 'lai[t]', 'plaî[t]'],
      question: 'O que acontece com a última letra?',
      options: ['Ela soa forte, como em português', 'Ela fica calada', 'Ela vira um i'],
      correct: 1,
      hint: 'Quase. Ouve as três de novo e repara só no finalzinho.',
      reveal: 'Isso. Em francês, a consoante do fim costuma ficar calada. Vous soa vu, lait soa lé, plaît soa plé.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. Lembra da letra do fim.',
      apply: [
        { fr: 'chocolat', pt: 'chocolate', options: ['chocolá', 'chocolát'], correct: 0 },
        { fr: 'petit', pt: 'pequeno', options: ['petít', 'petí'], correct: 1 },
      ],
      extra: 'Um detalhe: c, r, f e l costumam aparecer no fim. Pense na palavra inglesa careful. Por isso avec soa avék e bonjour termina com r.',
    },
    frame: {
      title: 'Monte o seu pedido', intro: 'Troque o que você quer pedir quantas vezes quiser. Cada frase toca sozinha.',
      template: "un ___, s'il vous plaît.", pt: 'um ___, por favor.', slot: ['café', 'thé', 'croissant', 'chocolat chaud', "verre d'eau"] },
  },
  {
    id: 'm02', chapter: 'ch1', pronoun: 'Ele',
    title: 'Me apresentar',
    can_do: 'dizer de onde você vem e quanto fala de francês',
    intro: 'Um vizinho puxa conversa no elevador. Hora de dizer quem você é.',
    lines: [
      ['Vizinho', '[Bonjour] ! [Vous] [habitez|habiter|mora] [ici] ?', 'Bom dia! Você mora aqui?'],
      ['Você', '[Oui]. [Je] [viens|venir|venho] [du] Brésil.', 'Sim. Venho do Brasil.'],
      ['Vizinho', '[Et] [vous] [parlez|parler|fala] [français] ?', 'E você fala francês?'],
      ['Você', "[Un] [peu], [mais] [j'|je][apprends|apprendre|estou aprendendo].", 'Um pouco, mas estou aprendendo.'],
      ['Vizinho', '[Parfait] ! [Un] [café], [un] [jour] ?', 'Perfeito! Um café qualquer dia?'],
      ['Você', '[Avec] [plaisir]. [Merci] !', 'Com prazer. Obrigado!'],
    ],
    key: {
      kind: 'leitura', ref: 'rr_ai', name: 'ai soa é', chapter: 3,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['franç[ai]s', 'm[ai]s', 'parf[ai]t'],
      question: 'Como soa o ai?',
      options: ['Ai, como em pai', 'É, como em pé', 'A, como em lá'],
      correct: 1,
      hint: 'Quase. Ouve as três de novo: ninguém diz ai.',
      reveal: 'Isso. Em francês, ai soa é aberto, como em pé. Français soa françé, mais soa mé, parfait soa parfé.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. Lembra: ai soa é.',
      apply: [
        { fr: 'vrai', pt: 'verdadeiro', options: ['vrái', 'vré'], correct: 1 },
        { fr: 'semaine', pt: 'semana', options: ['semén', 'semáine'], correct: 0 },
      ],
      extra: 'E repare no parfait: o t do fim fica calado, a chave do seu primeiro momento.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque a língua quantas vezes quiser. Cada frase toca sozinha.',
      template: 'vous parlez ___ ?', pt: 'você fala ___?', slot: ['français', 'anglais', 'allemand', 'portugais', 'luxembourgeois'],
    },
  },
  {
    id: 'm03', chapter: 'ch1', pair: 'vu/vous',
    title: 'Não entendi, pode repetir?',
    can_do: 'pedir para repetirem mais devagar',
    intro: 'Na padaria, a atendente fala rápido demais. Você pede para ela repetir.',
    lines: [
      ['Atendente', '[Bonjour] ! [Et] [pour] [vous] ?', 'Bom dia! E para você?'],
      ['Você', "[Un] [croissant], [s'il vous plaît].", 'Um croissant, por favor.'],
      ['Atendente', '[Sur place] [ou] [à emporter] ?', 'Para comer aqui ou para levar?'],
      ['Você', '[Pardon] ? [Vous] [pouvez|pouvoir|pode] [répéter] [plus] [lentement] ?', 'Desculpe? Pode repetir mais devagar?'],
      ['Atendente', '[Pour] [manger] [ici] [ou] [pour] [emporter] ?', 'Para comer aqui ou para levar?'],
      ['Você', '[Pour] [emporter]. [Merci] [beaucoup] !', 'Para levar. Muito obrigado!'],
    ],
    key: {
      kind: 'leitura', ref: 'rr_ou', name: 'ou soa u', chapter: 3,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['p[ou]r', 'v[ou]s', 'p[ou]vez'],
      question: 'Como soam as letras ou?',
      options: ['Ou, como em outro', 'U, como em tudo', 'Ô, como em avô'],
      correct: 1,
      hint: 'Quase. Ouve as três de novo e repara no som do meio.',
      reveal: 'Isso. Em francês, ou soa como o nosso u. Pour soa pur, vous soa vu, pouvez soa puvê.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. Lembra: ou soa u.',
      apply: [
        { fr: 'jour', pt: 'dia', options: ['jur', 'jôur'], correct: 0 },
        { fr: 'rouge', pt: 'vermelho', options: ['rôuj', 'ruj'], correct: 1 },
      ],
      extra: 'E o u sozinho? É outro som, com biquinho. Ele aparece daqui a pouco.',
    },
    frame: {
      title: 'Monte o seu pedido de ajuda', intro: 'Troque o verbo quantas vezes quiser. Cada frase toca sozinha.',
      template: 'vous pouvez ___ plus lentement ?', pt: 'pode ___ mais devagar?', slot: ['répéter', 'parler', 'expliquer', 'lire'],
    },
  },
  {
    id: 'm04', chapter: 'ch1',
    title: 'Quanto custa?',
    can_do: 'perguntar quanto é e pagar',
    intro: 'Hora de pagar o café. Você chama a atendente no balcão.',
    lines: [
      ['Você', '[Pardon], [je] [vous] [dois|devoir|devo] [combien] ?', 'Desculpe, quanto lhe devo?'],
      ['Atendente', "[Un] [café] [et] [un] [croissant]… [c'|ce][est|être|são] [trois] [euros|euro], [s'il vous plaît].", 'Um café e um croissant… são três euros, por favor.'],
      ['Você', '[Je] [peux|pouvoir|posso] [payer] [par] [carte] ?', 'Posso pagar com cartão?'],
      ['Atendente', '[Oui], [bien sûr]. [Voilà].', 'Sim, claro. Aqui está.'],
      ['Você', '[Merci]. [Bonne] [journée] !', 'Obrigado. Tenha um bom dia!'],
    ],
    key: {
      kind: 'leitura', ref: 'rr_oi', name: 'oi soa uá', chapter: 3,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['d[oi]s', 'tr[oi]s', 'v[oi]là'],
      question: 'Como soam as letras oi?',
      options: ['Ói, como em herói', 'Uá, como em água', 'Ô, como em avô'],
      correct: 1,
      hint: 'Quase. Ouve as três de novo e repara que o oi vira duas vogais diferentes.',
      reveal: 'Isso. Em francês, oi soa uá. Dois soa duá, trois soa truá, voilà soa vualá.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. Lembra: oi soa uá.',
      apply: [
        { fr: 'moi', pt: 'eu, mim', options: ['mói', 'muá'], correct: 1 },
        { fr: 'soir', pt: 'noite', options: ['suár', 'sóir'], correct: 0 },
      ],
      extra: 'O s de trois e o s de dois ficam calados, como você já viu.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o jeito de pagar quantas vezes quiser. Cada frase toca sozinha.',
      template: 'je peux payer par ___ ?', pt: 'posso pagar com ___?', slot: ['carte', 'chèque', 'virement', 'téléphone'],
    },
  },
  {
    id: 'm05', chapter: 'ch1',
    title: 'Onde fica?',
    can_do: 'perguntar onde fica um lugar e entender o caminho',
    intro: 'Você precisa de uma farmácia e pergunta para uma senhora na rua.',
    lines: [
      ['Você', "[Pardon], [madame]. [La] [pharmacie], [s'il vous plaît] ?", 'Desculpe, senhora. A farmácia, por favor?'],
      ['Senhora', '[Vous] [allez|aller|vai] [tout droit]…', 'Você vai em frente…'],
      ['Senhora', "…[et] [au] [bout] [de] [la] [rue], [à] [gauche].", '…e no fim da rua, à esquerda.'],
      ['Você', '[Tout droit], [puis] [à] [gauche]. [Merci] [beaucoup] !', 'Em frente, depois à esquerda. Muito obrigado!'],
      ['Senhora', '[Avec] [plaisir]. [Bonne] [journée] !', 'Com prazer. Tenha um bom dia!'],
    ],
    key: {
      kind: 'leitura', ref: 'rr_eau', name: 'eau e au soam ô', chapter: 3,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['[au]', 'g[au]che', 'b[eau]coup'],
      question: 'Como soam au e eau?',
      options: ['Au, como em mau', 'Ô, como em avô', 'Éu, como em chapéu'],
      correct: 1,
      hint: 'Quase. Ouve as três de novo: o som é um só.',
      reveal: 'Isso. Em francês, au e eau soam ô, fechado. Au soa ô, gauche soa gôch, beaucoup soa bôcu.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. Lembra: au e eau soam ô.',
      apply: [
        { fr: 'eau', pt: 'água', options: ['ô', 'éau'], correct: 0 },
        { fr: 'chaud', pt: 'quente', options: ['cháud', 'chô'], correct: 1 },
      ],
      extra: 'Três letras, um som só: eau, a água, soa apenas ô.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o lugar quantas vezes quiser. Cada frase toca sozinha.',
      template: "la ___, s'il vous plaît ?", pt: 'a ___, por favor?', slot: ['pharmacie', 'gare', 'banque', 'commune', 'boulangerie'],
    },
  },

  // ===========================================================================
  // Capítulo 2 · A Commune
  // ===========================================================================
  {
    id: 'm06', chapter: 'ch2',
    title: 'Chegar ao guichê',
    can_do: 'dizer no guichê o que você veio fazer',
    intro: 'Primeira vez na Commune. A funcionária do guichê chama você.',
    lines: [
      ['Funcionária', "[Bonjour]. [Qu'est-ce que] [je] [peux|pouvoir|posso] [faire] [pour] [vous] ?", 'Bom dia. O que posso fazer por você?'],
      ['Você', "[Bonjour]. [Je] [viens|venir|venho] [pour] [une] [déclaration] [d'|de][arrivée].", 'Bom dia. Venho fazer a declaração de chegada.'],
      ['Funcionária', '[Vous] [avez|avoir|tem] [un] [rendez-vous] ?', 'Você tem horário marcado?'],
      ['Você', '[Non], [pardon].', 'Não, desculpe.'],
      ['Funcionária', '[Pas de problème]. [Prenez|prendre|pegue] [un] [ticket] [et] [attendez|attendre|espere] [un] [moment].', 'Sem problema. Pegue uma senha e espere um pouco.'],
      ['Você', "[D'accord]. [Merci] !", 'Combinado. Obrigado!'],
    ],
    key: {
      kind: 'som', ref: 'rr_an', name: 'an e en soam ã', chapter: 4,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['r[en]dez-vous', 'att[en]dez', 'mom[en]t'],
      question: 'Como soa o en?',
      options: ['En, com o n bem marcado', 'Ã, como em lã', 'Ê, como em você'],
      correct: 1,
      hint: 'Quase. Ouve as três de novo e repara: o n não aparece.',
      reveal: 'Isso. En e an soam ã, nasal, e o n some. Rendez-vous soa rãdevú, attendez soa atãdê, moment soa momã.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. Lembra: en e an soam ã, sem o n.',
      apply: [
        { fr: 'enfant', pt: 'criança', options: ['ãfã', 'enfánt'], correct: 0 },
        { fr: 'dans', pt: 'dentro, em', options: ['dans', 'dã'], correct: 1 },
      ],
      extra: 'O mesmo acontece com am e em: chambre soa xãbr.',
    },
    frame: {
      title: 'Monte o seu pedido', intro: 'Troque o documento quantas vezes quiser. Cada frase toca sozinha.',
      template: 'je viens pour une ___.', pt: 'venho fazer uma ___.', slot: ['déclaration', 'inscription', 'attestation', 'demande'],
    },
  },
  {
    id: 'm07', chapter: 'ch2', pair: 'rue/roue',
    title: 'Dizer o seu endereço',
    can_do: 'dizer onde você mora',
    intro: 'Para a declaração, a funcionária pede o seu endereço.',
    lines: [
      ['Funcionária', "[Votre] [adresse], [s'il vous plaît] ?", 'Seu endereço, por favor?'],
      ['Você', "[J'|je][habite|habiter|moro] [au] [douze], [rue] [de] [la] [Gare|gare].", 'Moro no número doze da Rue de la Gare.'],
      ['Funcionária', '[Pardon] ? [Quelle|quel] [rue] ?', 'Desculpe? Qual rua?'],
      ['Você', "[Rue] [de] [la] [Gare|gare], [numéro] [douze]. [C'|ce][est|être|é] [une] [petite|petit|pequena] [rue].", 'Rue de la Gare, número doze. É uma rua pequena.'],
      ['Funcionária', '[Et] [à] [quel] [étage] ?', 'E em que andar?'],
      ['Você', '[Au] [troisième] [étage].', 'No terceiro andar.'],
    ],
    key: {
      kind: 'som', ref: 'rr_u', name: 'u com biquinho', chapter: 4,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['r[u]e', 'n[u]méro', '[u]ne'],
      question: 'Como soa o u francês?',
      options: ['U, como em tudo', 'I com biquinho, um som que o português não tem', 'Ô, como em avô'],
      correct: 1,
      hint: 'Quase. Ouve de novo: não é o nosso u. Diga i e faça bico.',
      reveal: 'Isso. O u francês é um i dito com os lábios em bico. O nosso u, em francês, se escreve ou: rue é rua, roue é roda.',
      apply_question: 'Qual é o som com biquinho?',
      apply_hint: 'Quase. O biquinho vem do u sozinho, não do ou.',
      apply: [
        { fr: 'tu', pt: 'você (informal)', options: ['tu, com biquinho', 'tu, como em tudo'], correct: 0 },
        { fr: 'bus', pt: 'ônibus', options: ['bus, como em ônibus', 'büs, com biquinho'], correct: 1 },
      ],
      extra: 'Truque: diga ii, deixe a língua parada e arredonde os lábios. Pronto, u francês.',
    },
    frame: {
      title: 'Monte o seu endereço', intro: 'Troque o número quantas vezes quiser. Cada frase toca sozinha.',
      template: "j'habite au ___, rue de la Gare.", pt: 'moro no número ___ da Rue de la Gare.', slot: ['douze', 'trois', 'cinq', 'huit', 'vingt'],
    },
  },
  {
    id: 'm08', chapter: 'ch2',
    title: 'Os documentos da família',
    can_do: 'entregar os documentos que pedirem',
    intro: 'Na Commune, a funcionária confere os papéis da família.',
    lines: [
      ['Funcionária', '[Pour] [la] [déclaration], [vous] [avez|avoir|tem] [vos|votre|seus] [passeports|passeport|passaportes] ?', 'Para a declaração, você tem os passaportes?'],
      ['Você', '[Oui]. [Voilà] [les] [passeports|passeport|passaportes].', 'Sim. Aqui estão os passaportes.'],
      ['Funcionária', '[Merci]. [Et] [une] [attestation] [de] [logement] ?', 'Obrigada. E um comprovante de moradia?'],
      ['Você', '[Voilà] [le] [contrat] [de] [bail].', 'Aqui está o contrato de aluguel.'],
      ['Funcionária', "[Parfait]. [Pour] [l'|le][inscription] [des|de|das] [enfants|enfant|crianças] [à] [l'|la][école], [c'|ce][est|être|é] [à côté].", 'Perfeito. Para a matrícula das crianças na escola, é aqui ao lado.'],
      ['Você', "[D'accord]. [Merci] [pour] [l'|la][information] !", 'Combinado. Obrigado pela informação!'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_cao_tion', name: '-ção vira -tion', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'déclara[tion]', pt: 'declaração' }, { fr: 'attesta[tion]', pt: 'atestação' }, { fr: 'informa[tion]', pt: 'informação' }],
      question: 'O que o -tion do francês é no português?',
      options: ['-ção', '-dade', '-mente'],
      correct: 0,
      hint: 'Quase. Diga declaração em voz alta e compare com o fim de déclaration.',
      reveal: 'Isso. Quase toda palavra em -ção tem uma irmã francesa em -tion, que soa ciõ. Declaração, déclaration; informação, information.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ção por -tion.',
      apply: [
        { fr: 'solution', pt: 'solução', options: ['solution', 'solução'], correct: 0 },
        { fr: 'question', pt: 'questão', options: ['questão', 'question'], correct: 1 },
      ],
      extra: 'São centenas: nation, situation, attention, réservation. Você já conhece todas.',
    },
    frame: {
      title: 'Monte a sua frase', intro: 'Troque o documento quantas vezes quiser. Cada frase toca sozinha.',
      template: 'voilà le ___.', pt: 'aqui está o ___.', slot: ['passeport', 'contrat', 'document', 'certificat', 'formulaire'],
    },
  },
  {
    id: 'm09', chapter: 'ch2', pair: 'beau/bon',
    title: 'Marcar um horário',
    can_do: 'marcar um horário por telefone',
    intro: 'Você liga para a Commune para voltar com o documento que faltou.',
    lines: [
      ['Você', "[Bonjour]. [Je] [voudrais|vouloir|queria] [un] [rendez-vous], [s'il vous plaît].", 'Bom dia. Eu queria marcar um horário, por favor.'],
      ['Funcionária', "[Oui]. [Lundi] [à] [onze] [heures|heure], [c'|ce][est|être|é] [bon] [pour] [vous] ?", 'Sim. Segunda às onze horas, está bom para você?'],
      ['Você', "[Non], [lundi] [je] [travaille|travailler|trabalho]. [Mardi], [c'|ce][est|être|é] [possible] ?", 'Não, segunda eu trabalho. Terça, é possível?'],
      ['Funcionária', '[Mardi] [à] [neuf] [heures|heure] ?', 'Terça às nove horas?'],
      ['Você', "[C'|ce][est|être|é] [bon]. [Merci], [à] [mardi] !", 'Está bom. Obrigado, até terça!'],
    ],
    key: {
      kind: 'som', ref: 'rr_on', name: 'on soa õ', chapter: 4,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['b[on]', 'n[on]', '[on]ze'],
      question: 'Como soa o on?',
      options: ['On, com o n bem marcado', 'Õ, como em bom', 'U, como em tudo'],
      correct: 1,
      hint: 'Quase. Ouve as três de novo e repara: o n some.',
      reveal: 'Isso. On soa õ, como no nosso bom. Bon soa bõ, non soa nõ, onze soa õz.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. Lembra: on soa õ, sem o n.',
      apply: [
        { fr: 'maison', pt: 'casa', options: ['mezõ', 'mezón'], correct: 0 },
        { fr: 'nom', pt: 'nome', options: ['nom', 'nõ'], correct: 1 },
      ],
      extra: 'Com m é igual: nom soa nõ.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o dia quantas vezes quiser. Cada frase toca sozinha.',
      template: "___, c'est possible ?", pt: '___, é possível?', slot: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
    },
  },

  // ===========================================================================
  // Capítulo 3 · Creche e CSA
  // ===========================================================================
  {
    id: 'm10', chapter: 'ch3',
    title: 'Primeiro dia na creche',
    can_do: 'apresentar seu filho na creche',
    intro: 'Primeiro dia da Léa na creche. A educadora recebe vocês na porta.',
    lines: [
      ['Educadora', '[Bonjour] ! [Vous] [êtes|être|são] [la] [famille] [de] Léa ?', 'Bom dia! Vocês são a família da Léa?'],
      ['Você', "[Oui], [bonjour]. [C'|ce][est|être|é] [son] [premier] [jour].", 'Sim, bom dia. É o primeiro dia dela.'],
      ['Educadora', '[Bienvenue] ! [Et] [toi], [tu] [es|être|é] Léa ? [Tu] [veux|vouloir|quer] [jouer] ?', 'Bem-vindos! E você, é a Léa? Quer brincar?'],
      ['Você', '[Elle] [est|être|é] [un] [peu] [timide].', 'Ela é um pouco tímida.'],
      ['Educadora', '[Pas de problème]. [Vous] [pouvez|pouvoir|pode] [rester] [un] [moment] [avec] [elle].', 'Sem problema. Você pode ficar um pouco com ela.'],
      ['Você', "[Merci]. [À tout à l'heure], Léa !", 'Obrigado. Até daqui a pouco, Léa!'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_tu_vous', name: 'tu ou vous', chapter: 6,
      intro: 'Ouça como a educadora fala com você e com a Léa.',
      examples: ['[Vous] êtes', '[tu] es', '[Tu] veux'],
      question: 'Por que ela usa vous com você e tu com a Léa?',
      options: ['Vous é o educado, para adultos; tu, para crianças e gente próxima', 'Vous é mais carinhoso que tu', 'Tanto faz, os dois são iguais'],
      correct: 0,
      hint: 'Quase. Pense em quem é adulto e quem é criança na cena.',
      reveal: 'Isso. Vous é o você educado, para quem você não conhece. Tu é o próximo, para crianças, amigos e família.',
      apply_question: 'Com quem você fala assim?',
      apply_hint: 'Quase. Tu é para crianças e gente próxima.',
      apply: [
        { fr: "Comment tu t'appelles ?", pt: 'Como você se chama?', options: ['Com uma criança', 'Com o funcionário do banco'], correct: 0 },
        { fr: 'Vous avez un stylo ?', pt: 'O senhor tem uma caneta?', options: ['Com a sua filha', 'Com alguém que você não conhece'], correct: 1 },
      ],
      extra: 'Na dúvida, vous. Se a pessoa quiser mais proximidade, ela mesma propõe o tu.',
    },
    frame: {
      title: 'Monte uma pergunta para a Léa', intro: 'Troque a atividade quantas vezes quiser. Cada frase toca sozinha.',
      template: 'tu veux ___ ?', pt: 'você quer ___?', slot: ['jouer', 'manger', 'dormir', 'venir'],
    },
  },
  {
    id: 'm11', chapter: 'ch3',
    title: 'Avisar que a criança está doente',
    can_do: 'avisar que a criança está doente e não vai',
    intro: 'A Léa acordou com febre. Você liga para a creche antes das oito.',
    lines: [
      ['Você', "[Bonjour], [c'|ce][est|être|é] [la] [famille] [de] Léa.", 'Bom dia, é a família da Léa.'],
      ['Educadora', '[Bonjour] ! [Ça va] ?', 'Bom dia! Tudo bem?'],
      ['Você', "[Non]. Léa [est|être|está] [malade], [elle] [a|avoir|tem] [de] [la] [fièvre]. [Elle] [ne] [vient|venir|vem] [pas] [aujourd'hui].", 'Não. A Léa está doente, está com febre. Ela não vem hoje.'],
      ['Educadora', "[Ce] [n'|ne][est|être|é] [pas] [grave]. [Elle] [mange|manger|come] [bien] ?", 'Não é grave. Ela está comendo bem?'],
      ['Você', '[Non], [elle] [ne] [mange|manger|come] [pas] [beaucoup].', 'Não, ela não come muito.'],
      ['Educadora', '[Merci] [de] [prévenir]. [Bon] [courage] !', 'Obrigada por avisar. Força!'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_ne_pas', name: 'ne… pas', chapter: 9,
      intro: 'Ouça estas três frases da conversa.',
      examples: ['elle [ne] vient [pas]', "Ce [n']est [pas]", 'elle [ne] mange [pas]'],
      question: 'Como se diz não em francês?',
      options: ['Só com pas, antes do verbo', 'Com ne antes do verbo e pas depois', 'Com non no fim da frase'],
      correct: 1,
      hint: 'Quase. Repare onde ficam o ne e o pas em relação ao verbo.',
      reveal: 'Isso. O não francês tem duas partes que abraçam o verbo: ne antes, pas depois. Antes de vogal, ne vira n’.',
      apply_question: 'O que quer dizer?',
      apply_hint: 'Quase. Ne… pas é o não.',
      apply: [
        { fr: 'Je ne comprends pas.', pt: 'Não entendo.', options: ['Não entendo.', 'Entendo.'], correct: 0 },
        { fr: 'Il ne dort pas.', pt: 'Ele não dorme.', options: ['Ele dorme.', 'Ele não dorme.'], correct: 1 },
      ],
      extra: 'Na fala rápida, o ne às vezes some: je sais pas. O pas nunca some.',
    },
    frame: {
      title: 'Monte o seu aviso', intro: 'Troque o dia quantas vezes quiser. Cada frase toca sozinha.',
      template: 'elle ne vient pas ___.', pt: 'ela não vem ___.', slot: ["aujourd'hui", 'demain', 'lundi', 'mardi', 'mercredi'],
    },
  },
  {
    id: 'm12', chapter: 'ch3',
    title: 'Combinar o horário de buscar',
    can_do: 'combinar a que horas você vem buscar a criança',
    intro: 'De manhã, na porta da creche, a educadora pergunta quem vem buscar a Léa.',
    lines: [
      ['Educadora', '[Vous] [venez|venir|vem] [chercher] Léa [à] [quelle|quel] [heure] ?', 'A que horas você vem buscar a Léa?'],
      ['Você', "[Aujourd'hui], [je] [vais|aller|vou] [venir] [à] [seize] [heures|heure].", 'Hoje eu vou vir às dezesseis horas.'],
      ['Educadora', "[D'accord]. [Et] [demain] ?", 'Combinado. E amanhã?'],
      ['Você', '[Demain], [sa|son|a] [grand-mère] [va|aller|vai] [venir] [après] [le] [travail].', 'Amanhã a avó dela vai vir depois do trabalho.'],
      ['Educadora', '[Très] [bien]. [On] [va|aller|vai] [faire] [une] [petite|petit|pequena] [fête] [demain].', 'Muito bem. A gente vai fazer uma festinha amanhã.'],
      ['Você', '[Super] ! Léa [va|aller|vai] [adorer].', 'Que ótimo! A Léa vai adorar.'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_aller', name: 'ir + verbo', chapter: 11,
      intro: 'Ouça estas três frases da conversa.',
      examples: ['je [vais] venir', 'on [va] faire', 'Léa [va] adorer'],
      question: 'Como o francês fala do que vai acontecer?',
      options: ['Com o verbo ir e depois a ação, como vou vir', 'Mudando o fim do verbo', 'Com a palavra demain antes'],
      correct: 0,
      hint: 'Quase. Compare je vais venir com o português eu vou vir.',
      reveal: 'Isso. É igual ao português: ir e depois a ação. Je vais venir, eu vou vir. On va faire, a gente vai fazer.',
      apply_question: 'O que quer dizer?',
      apply_hint: 'Quase. Vais e va são o verbo ir.',
      apply: [
        { fr: 'Je vais manger.', pt: 'Eu vou comer.', options: ['Eu vou comer.', 'Eu comi.'], correct: 0 },
        { fr: 'Elle va dormir.', pt: 'Ela vai dormir.', options: ['Ela dormiu.', 'Ela vai dormir.'], correct: 1 },
      ],
      extra: 'Je vais, tu vas, il va, on va: as formas mudam pouco, e o verbo da ação fica igual.',
    },
    frame: {
      title: 'Monte o seu combinado', intro: 'Troque a hora quantas vezes quiser. Cada frase toca sozinha.',
      template: 'je vais venir à ___ heures.', pt: 'vou vir às ___ horas.', slot: ['quatre', 'cinq', 'six', 'seize'],
    },
  },
  {
    id: 'm13', chapter: 'ch3',
    title: 'Conversar com a educadora',
    can_do: 'perguntar como foi o dia da criança',
    intro: 'No fim da tarde, você busca a Léa e pergunta como foi o dia.',
    lines: [
      ['Você', '[Bonjour] ! [Ça va] ? Léa [a|avoir] [bien] [dormi|dormir|dormiu] ?', 'Oi! Tudo bem? A Léa dormiu bem?'],
      ['Educadora', '[Oui], [elle] [a|avoir] [dormi|dormir|dormiu] [une] [heure] [après] [le] [repas].', 'Sim, ela dormiu uma hora depois do almoço.'],
      ['Você', '[Et] [elle] [a|avoir] [mangé|manger|comeu] [du] [poisson] ?', 'E ela comeu o peixe?'],
      ['Educadora', '[Oui], [tout] ! [Et] [elle] [a|avoir] [beaucoup] [joué|jouer|brincou].', 'Sim, tudo! E ela brincou muito.'],
      ['Você', '[Super]. [Merci] [pour] [tout] !', 'Que ótimo. Obrigado por tudo!'],
      ['Educadora', '[Avec] [plaisir]. [À] [demain], Léa !', 'Com prazer. Até amanhã, Léa!'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_passe', name: 'o passado com avoir', chapter: 12,
      intro: 'Ouça estas três frases da conversa.',
      examples: ['elle [a] dorm[i]', 'elle [a] mang[é]', '[a] beaucoup jou[é]'],
      question: 'Como o francês conta o que já aconteceu?',
      options: ['Com a (de avoir) e o verbo com outro final: a mangé', 'Com o verbo ir: va manger', 'Não muda nada'],
      correct: 0,
      hint: 'Quase. Repare no a antes do verbo e no fim do verbo.',
      reveal: 'Isso. Para o passado, o francês usa avoir e o verbo com outro final: elle a mangé, ela comeu. Verbos em -er terminam em -é, com o mesmo som.',
      apply_question: 'O que quer dizer?',
      apply_hint: 'Quase. A + verbo terminado em -é é passado.',
      apply: [
        { fr: "J'ai parlé.", pt: 'Eu falei.', options: ['Eu falei.', 'Eu vou falar.'], correct: 0 },
        { fr: 'Il a travaillé.', pt: 'Ele trabalhou.', options: ['Ele trabalha.', 'Ele trabalhou.'], correct: 1 },
      ],
      extra: 'Parece o nosso tenho comido, mas quer dizer comi: é o passado do dia a dia.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque a comida quantas vezes quiser. Cada frase toca sozinha.',
      template: 'elle a mangé du ___ ?', pt: 'ela comeu ___?', slot: ['poisson', 'poulet', 'riz', 'fromage', 'pain'],
    },
  },
  // ===========================================================================
  // Capítulo 4 · Supermercado
  // ===========================================================================
  {
    id: 'm14', chapter: 'ch4', pronoun: 'Ele', pair: 'vin/vent',
    title: 'Achar um produto',
    can_do: 'perguntar onde está um produto',
    intro: 'Primeira compra grande no supermercado. Você não acha o pão e pergunta a um funcionário.',
    lines: [
      ['Você', "[Pardon], [monsieur]. [Le] [pain], [s'il vous plaît] ?", 'Desculpe, senhor. O pão, por favor?'],
      ['Funcionário', "[Le] [pain] ? [C'|ce][est|être|fica] [au] [fond], [à] [droite].", 'O pão? Fica no fundo, à direita.'],
      ['Você', '[Et] [le] [vin] ?', 'E o vinho?'],
      ['Funcionário', "[Le] [vin], [c'|ce][est|être|fica] [à côté] [du] [pain].", 'O vinho fica ao lado do pão.'],
      ['Você', '[Merci]. [Et] [vous] [avez|avoir|tem] [du] [lait] [le] [matin] ?', 'Obrigado. E vocês têm leite de manhã?'],
      ['Funcionário', "[Oui], [tous|tout|todos] [les] [matins|matin|as manhãs].", 'Sim, todas as manhãs.'],
    ],
    key: {
      kind: 'som', ref: 'rr_in', name: 'in e ain soam ẽ', chapter: 4,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['p[ain]', 'v[in]', 'mat[in]'],
      question: 'Como soam ain e in?',
      options: ['Ẽ, como em bem', 'In, com o n bem marcado', 'Ai, como em pai'],
      correct: 0,
      hint: 'Quase. Ouve as três de novo: o n some, e a vogal fica nasal.',
      reveal: 'Isso. In e ain soam ẽ, nasal, como no nosso bem. Pain soa pẽ, vin soa vẽ, matin soa matẽ.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. Lembra: in e ain soam ẽ.',
      apply: [
        { fr: 'main', pt: 'mão', options: ['mẽ', 'máin'], correct: 0 },
        { fr: 'jardin', pt: 'jardim', options: ['jardín', 'jardẽ'], correct: 1 },
      ],
      extra: 'Agora você tem as três nasais: ã em enfant, õ em bon, ẽ em pain.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o produto quantas vezes quiser. Cada frase toca sozinha.',
      template: 'vous avez du ___ ?', pt: 'vocês têm ___?', slot: ['lait', 'pain', 'riz', 'fromage', 'beurre'],
    },
  },
  {
    id: 'm15', chapter: 'ch4',
    title: 'No balcão de frios',
    can_do: 'pedir uma quantidade no balcão',
    intro: 'No balcão de queijos e frios, a vendedora chama o próximo. É você.',
    lines: [
      ['Vendedora', "[Bonjour] ! [Qu'est-ce que] [je] [vous] [sers|servir|sirvo] ?", 'Bom dia! O que eu lhe sirvo?'],
      ['Você', "[Un] [morceau] [de] [fromage], [s'il vous plaît].", 'Um pedaço de queijo, por favor.'],
      ['Vendedora', '[Un] [petit] [morceau] ? [Et] [avec] [ça] ?', 'Um pedaço pequeno? E o que mais?'],
      ['Você', '[Oui]. [Et] [une] [tranche] [de] [jambon].', 'Sim. E uma fatia de presunto.'],
      ['Vendedora', '[Voilà]. [Le] [fromage] [et] [le] [jambon]… [ça fait] [sept] [euros|euro].', 'Pronto. O queijo e o presunto… dá sete euros.'],
      ['Você', '[Merci], [et] [bonne] [journée] !', 'Obrigado, e tenha um bom dia!'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_genero', name: 'le, la, un, une', chapter: 7,
      intro: 'Ouça estas três partes da conversa.',
      examples: ['[un] morceau', '[une] tranche', '[le] fromage'],
      question: 'Por que un morceau, mas une tranche?',
      options: ['Morceau é masculino e tranche é feminino, como pedaço e fatia', 'Une é mais educado', 'Depende da quantidade'],
      correct: 0,
      hint: 'Quase. Pense no português: um pedaço, uma fatia.',
      reveal: 'Isso. Un e le vão com palavras masculinas; une e la, com femininas. Quase sempre o gênero é o mesmo do português: um pedaço, un morceau; uma fatia, une tranche.',
      apply_question: 'Un ou une?',
      apply_hint: 'Quase. Pense no gênero em português.',
      apply: [
        { fr: 'bouteille', pt: 'garrafa', options: ['un', 'une'], correct: 1 },
        { fr: 'gâteau', pt: 'bolo', options: ['un', 'une'], correct: 0 },
      ],
      extra: 'Algumas trocam de gênero, como la voiture, o carro. Quando aparecer, o app avisa.',
    },
    frame: {
      title: 'Monte o seu pedido', intro: 'Troque o que você quer quantas vezes quiser. Cada frase toca sozinha.',
      template: 'une tranche de ___.', pt: 'uma fatia de ___.', slot: ['jambon', 'fromage', 'pain', 'gâteau'],
    },
  },
  {
    id: 'm16', chapter: 'ch4',
    title: 'Devolver as garrafas',
    can_do: 'perguntar onde devolver as garrafas',
    intro: 'Você trouxe as garrafas vazias de volta e procura onde deixá-las.',
    lines: [
      ['Você', '[Bonjour]. [Où] [est|être|fica] [la] [machine] [pour] [les] [bouteilles|bouteille|garrafas] ?', 'Bom dia. Onde fica a máquina para as garrafas?'],
      ['Funcionária', "[À] [l'|la][entrée], [à] [gauche]. [C'|ce][est|être|é] [automatique].", 'Na entrada, à esquerda. É automática.'],
      ['Você', '[Et] [pour] [le] [plastique] ?', 'E para o plástico?'],
      ['Funcionária', "[C'|ce][est|être|é] [la] [même] [machine]. [Après], [vous] [avez|avoir|recebe] [un] [ticket].", 'É a mesma máquina. Depois você recebe um tíquete.'],
      ['Você', '[Pratique] ! [Et] [le] [ticket], [je] [le] [donne|donner|entrego] [à] [la] [caisse] ?', 'Que prático! E o tíquete, eu entrego no caixa?'],
      ['Funcionária', '[Oui], [exactement].', 'Sim, exatamente.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_ico_ique', name: '-ico vira -ique', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'automat[ique]', pt: 'automático' }, { fr: 'plast[ique]', pt: 'plástico' }, { fr: 'prat[ique]', pt: 'prático' }],
      question: 'O que o -ique do francês é no português?',
      options: ['-ico ou -ica', '-ível', '-eiro'],
      correct: 0,
      hint: 'Quase. Diga plástico e compare com plastique.',
      reveal: 'Isso. As palavras em -ico e -ica viram -ique em francês, com som de ik. Automático, automatique; prático, pratique.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ico ou -ica por -ique.',
      apply: [
        { fr: 'musique', pt: 'música', options: ['musique', 'música'], correct: 0 },
        { fr: 'électrique', pt: 'elétrico', options: ['elétrico', 'électrique'], correct: 1 },
      ],
      extra: 'O som do fim é ik: pratique soa pratík.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o lugar quantas vezes quiser. Cada frase toca sozinha.',
      template: 'où est la ___ ?', pt: 'onde fica a ___?', slot: ['machine', 'caisse', 'sortie', 'boulangerie'],
    },
  },
  {
    id: 'm17', chapter: 'ch4',
    title: 'Pagar no caixa',
    can_do: 'responder às perguntas do caixa',
    intro: 'Na fila do caixa, a atendente faz as perguntas de sempre.',
    lines: [
      ['Caixa', '[Bonjour] ! [Vous] [avez|avoir|tem] [la] [carte] [du] [magasin] ?', 'Bom dia! Você tem o cartão da loja?'],
      ['Você', '[Non]. [Est-ce que] [je] [peux|pouvoir|posso] [la] [faire] [maintenant] ?', 'Não. Posso fazer agora?'],
      ['Caixa', '[Oui], [bien sûr]. [Vous] [voulez|vouloir|quer] [un] [sac] ?', 'Sim, claro. Você quer uma sacola?'],
      ['Você', "[Non], [merci]. [J'|je][ai|avoir|tenho] [un] [sac].", 'Não, obrigado. Tenho sacola.'],
      ['Caixa', '[Ça fait] [vingt] [euros|euro]. [Vous] [payez|payer|paga] [comment] ?', 'Dá vinte euros. Como você paga?'],
      ['Você', "[Par] [carte], [s'il vous plaît].", 'Com cartão, por favor.'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_perguntas', name: 'perguntar sem complicar', chapter: 10,
      intro: 'Ouça estas três perguntas da conversa.',
      examples: ['[Vous avez] la carte', '[Est-ce que] je peux', 'vous payez [comment]'],
      question: 'Como se faz pergunta em francês?',
      options: ['Com a voz subindo, com est-ce que ou com uma palavra de pergunta', 'Só invertendo o verbo', 'Só no fim da frase, com hein'],
      correct: 0,
      hint: 'Quase. Repare: vous avez é igual à afirmação, só que com a voz subindo.',
      reveal: 'Isso. O jeito mais simples é o do português: a mesma frase, com a voz subindo. Est-ce que na frente também marca a pergunta, e comment, où ou quand dizem o que se quer saber.',
      apply_question: 'O que quer dizer?',
      apply_hint: 'Quase. Repare na palavra de pergunta.',
      apply: [
        { fr: "C'est où ?", pt: 'Fica onde?', options: ['Fica onde?', 'Fica aqui.'], correct: 0 },
        { fr: "Est-ce que c'est loin ?", pt: 'É longe?', options: ['É longe.', 'É longe?'], correct: 1 },
      ],
      extra: 'Existe também a inversão, vous payez → payez-vous, mais formal. Você não precisa dela para se virar.',
    },
    frame: {
      title: 'Monte a pergunta da caixa', intro: 'Troque o que ela oferece quantas vezes quiser. Cada frase toca sozinha.',
      template: 'vous voulez un ___ ?', pt: 'você quer um(a) ___?', slot: ['sac', 'ticket', 'café', 'croissant'],
    },
  },

  // ===========================================================================
  // Capítulo 5 · Transporte
  // ===========================================================================
  {
    id: 'm18', chapter: 'ch5', pronoun: 'Ele', pair: 'deux/des',
    title: 'Qual ônibus vai?',
    can_do: 'perguntar qual ônibus pegar',
    intro: 'No ponto de ônibus, você não sabe qual linha vai para a estação.',
    lines: [
      ['Você', "[Pardon], [monsieur]. [Le] [bus] [pour] [la] [gare], [c'|ce][est|être|é] [lequel] ?", 'Desculpe, senhor. O ônibus para a estação, qual é?'],
      ['Senhor', "[C'|ce][est|être|é] [le] [deux]. [Il] [passe|passer|passa] [dans] [deux] [minutes|minute].", 'É o dois. Ele passa em dois minutos.'],
      ['Você', '[Le] [deux] ? [Il] [a|avoir|está] [du] [retard] ?', 'O dois? Está atrasado?'],
      ['Senhor', "[Un] [peu]. [Mais] [le] [seize], [c'|ce][est|être|é] [plus] [rapide].", 'Um pouco. Mas o dezesseis é mais rápido.'],
      ['Você', '[Merci], [monsieur]. [Je] [prends|prendre|pego] [le] [deux], [alors].', 'Obrigado, senhor. Então eu pego o dois.'],
    ],
    key: {
      kind: 'som', ref: 'rr_eu', name: 'eu soa ê com biquinho', chapter: 4,
      intro: 'Ouça estas três palavras da conversa.',
      examples: ['d[eu]x', 'p[eu]', 'monsi[eu]r'],
      question: 'Como soa o eu?',
      options: ['Éu, como em chapéu', 'Ê com os lábios em bico', 'U, como em tudo'],
      correct: 1,
      hint: 'Quase. Ouve de novo: é uma vogal só, sem u no fim.',
      reveal: 'Isso. Eu é um ê dito com os lábios em bico, um som que o português não tem. Deux soa dê com biquinho, peu soa pê com biquinho.',
      apply_question: 'Qual se aproxima mais?',
      apply_hint: 'Quase. Uma vogal só, com biquinho.',
      apply: [
        { fr: 'bleu', pt: 'azul', options: ['blê, com biquinho', 'bléu'], correct: 0 },
        { fr: 'jeudi', pt: 'quinta-feira', options: ['jéudi', 'jêdi, com biquinho'], correct: 1 },
      ],
      extra: 'Deux (dois) e des (uns) só se diferenciam por esse biquinho. Vale treinar no Como funciona.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o destino quantas vezes quiser. Cada frase toca sozinha.',
      template: "le bus pour la ___, c'est lequel ?", pt: 'o ônibus para a ___, qual é?', slot: ['gare', 'commune', 'crèche', 'banque', 'pharmacie'],
    },
  },
  {
    id: 'm19', chapter: 'ch5', pronoun: 'Ele',
    title: 'O ônibus atrasou',
    can_do: 'entender um aviso de atraso',
    intro: 'Dentro do ônibus, o motorista faz um anúncio. Você vai até ele perguntar.',
    lines: [
      ['Motorista', '[Mesdames et messieurs], [nous] [avons|avoir|temos] [un] [petit] [retard].', 'Senhoras e senhores, estamos com um pequeno atraso.'],
      ['Você', '[Pardon], [monsieur]. [Il y a] [un] [problème] ?', 'Desculpe, senhor. Tem algum problema?'],
      ['Motorista', '[Il y a] [des|de|umas] [travaux]. [Dix] [minutes|minute] [de] [retard].', 'Tem obras. Dez minutos de atraso.'],
      ['Você', '[Dix] [minutes|minute] ? [Je] [vais|aller|vou] [être] [en] [retard] !', 'Dez minutos? Vou chegar atrasado!'],
      ['Motorista', '[Vous] [allez|aller|vai] [où] ?', 'Você vai para onde?'],
      ['Você', '[Chez] [un] [ami], [près] [de] [la] [gare].', 'Na casa de um amigo, perto da estação.'],
    ],
    key: {
      kind: 'som', ref: 'rr_liaison', name: 'a letra calada acorda', chapter: 5,
      intro: 'Ouça estes três pedaços da conversa.',
      examples: ['nou[s] avons', 'vou[s] allez', 'u[n] ami'],
      question: 'O que acontece com o s de nous antes de avons?',
      options: ['Continua calado', 'Acorda e soa z, ligando as duas palavras', 'Vira um i'],
      correct: 1,
      hint: 'Quase. Ouve de novo: nous avons soa como uma palavra só.',
      reveal: 'Isso. Quando a palavra seguinte começa com vogal, a letra calada acorda e se liga a ela. Nous avons soa nuzavõ; vous allez, vuzalê; un ami, ẽnamí. O arco embaixo das palavras marca essas ligações.',
      apply_question: 'Como soa?',
      apply_hint: 'Quase. A letra do fim acorda antes de vogal.',
      apply: [
        { fr: 'les enfants', pt: 'as crianças', options: ['lê ãfã', 'lezãfã'], correct: 1 },
        { fr: 'un ami', pt: 'um amigo', options: ['ẽnamí', 'ẽ amí'], correct: 0 },
      ],
      extra: 'Depois de et (e), nunca liga: un café et un croissant.',
    },
    frame: {
      title: 'Monte a sua resposta', intro: 'Troque a pessoa quantas vezes quiser. Cada frase toca sozinha.',
      template: 'chez un ___.', pt: 'na casa de um ___.', slot: ['ami', 'médecin', 'dentiste', 'collègue'],
    },
  },
  {
    id: 'm20', chapter: 'ch5',
    title: 'Descer no ponto certo',
    can_do: 'perguntar onde você está e onde descer',
    intro: 'O ônibus anda e você perde a conta dos pontos. Pergunta à senhora do lado.',
    lines: [
      ['Você', '[Pardon], [madame]. [Nous] [sommes|être|estamos] [où] ?', 'Desculpe, senhora. Onde estamos?'],
      ['Senhora', '[Nous] [sommes|être|estamos] [à] Hamilius.', 'Estamos em Hamilius.'],
      ['Você', "[Je] [vais|aller|vou] [à] [la] [gare]. [C'|ce][est|être|é] [loin] ?", 'Vou para a estação. É longe?'],
      ['Senhora', "[Non], [c'|ce][est|être|é] [tout] [près]. [Vous] [êtes|être|está] [à] [trois] [arrêts|arrêt|pontos].", 'Não, é bem perto. Você está a três pontos.'],
      ['Você', '[Trois] [arrêts|arrêt|pontos]. [Merci], [vous] [êtes|être|é] [gentille|gentil|gentil] !', 'Três pontos. Obrigado, a senhora é gentil!'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_etre', name: 'être: ser e estar', chapter: 8,
      intro: 'Ouça estes três pedaços da conversa.',
      examples: ['nous [sommes]', 'vous [êtes]', "c'[est]"],
      question: 'O que sommes, êtes e est têm em comum?',
      options: ['São formas de être, que é ser e também estar', 'São formas de avoir, ter', 'São nomes de pontos de ônibus'],
      correct: 0,
      hint: 'Quase. Nous sommes où quer dizer onde estamos.',
      reveal: 'Isso. São formas de être, um verbo só para ser e estar: nous sommes, nós somos ou estamos; vous êtes, você é ou está; c’est, é.',
      apply_question: 'O que quer dizer?',
      apply_hint: 'Quase. Être é ser ou estar.',
      apply: [
        { fr: 'Il est tard.', pt: 'É tarde.', options: ['É tarde.', 'Tem tarde.'], correct: 0 },
        { fr: 'Nous sommes en retard.', pt: 'Estamos atrasados.', options: ['Temos atraso de ônibus.', 'Estamos atrasados.'], correct: 1 },
      ],
      extra: 'Je suis, tu es, il est, nous sommes, vous êtes, ils sont: as formas mais usadas da língua.',
    },
    frame: {
      title: 'Monte o seu destino', intro: 'Troque o lugar quantas vezes quiser. Cada frase toca sozinha.',
      template: 'je vais à la ___.', pt: 'vou para a ___.', slot: ['gare', 'banque', 'pharmacie', 'commune', 'crèche'],
    },
  },
  {
    id: 'm21', chapter: 'ch5',
    title: 'Pegar o trem',
    can_do: 'perguntar a plataforma e se precisa de bilhete',
    intro: 'Na estação, você quer o trem para Esch e pergunta no balcão de informações.',
    lines: [
      ['Você', "[Bonjour]. [Le] [train] [pour] Esch, [c'|ce][est|être|é] [quel] [quai] ?", 'Bom dia. O trem para Esch, é qual plataforma?'],
      ['Funcionária', "[Quai] [trois]. [Regardez|regarder|olhe] [l'|le][horaire], [là-bas].", 'Plataforma três. Olhe o horário, ali.'],
      ['Você', '[Il] [faut|falloir|precisa] [un] [billet] ?', 'Precisa de bilhete?'],
      ['Funcionária', "[Non], [ce] [n'|ne][est|être|é] [pas] [nécessaire]. [C'|ce][est|être|é] [gratuit].", 'Não, não é necessário. É grátis.'],
      ['Você', "[Gratuit] ? [C'|ce][est|être|é] [extraordinaire] !", 'Grátis? Que extraordinário!'],
      ['Funcionária', '[Oui], [sauf] [en] [première|premier|primeira] [classe].', 'Sim, menos na primeira classe.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_ario_aire', name: '-ário vira -aire', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'hor[aire]', pt: 'horário' }, { fr: 'nécess[aire]', pt: 'necessário' }, { fr: 'extraordin[aire]', pt: 'extraordinário' }],
      question: 'O que o -aire do francês é no português?',
      options: ['-ário ou -ária', '-eiro', '-ável'],
      correct: 0,
      hint: 'Quase. Diga horário e compare com horaire.',
      reveal: 'Isso. Palavras em -ário e -ária viram -aire, que soa ér. Horário, horaire; necessário, nécessaire.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ário por -aire.',
      apply: [
        { fr: 'salaire', pt: 'salário', options: ['salaire', 'salário'], correct: 0 },
        { fr: 'dictionnaire', pt: 'dicionário', options: ['dicionário', 'dictionnaire'], correct: 1 },
      ],
      extra: 'Como ai soa é, o -aire soa ér: salaire soa salér.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o que você quer saber quantas vezes quiser. Cada frase toca sozinha.',
      template: 'il faut un ___ ?', pt: 'precisa de um(a) ___?', slot: ['billet', 'ticket', 'rendez-vous', 'formulaire', 'passeport'],
    },
  },
  // ===========================================================================
  // Capítulo 6 · Médico e farmácia
  // ===========================================================================
  {
    id: 'm22', chapter: 'ch6',
    title: 'Marcar consulta',
    can_do: 'marcar uma consulta para a criança',
    intro: 'A Léa está com febre. Você liga para o consultório do pediatra.',
    lines: [
      ['Secretária', '[Bonjour], [cabinet|cabinet|consultório] [du] [pédiatre].', 'Bom dia, consultório do pediatra.'],
      ['Você', "[Bonjour]. [Ma] [fille] [a|avoir|está com] [de] [la] [fièvre]. [Vous] [avez|avoir|tem] [une] [place] [aujourd'hui] ?", 'Bom dia. Minha filha está com febre. Vocês têm um horário hoje?'],
      ['Secretária', '[Elle] [a|avoir|tem] [quel] [âge] ?', 'Quantos anos ela tem?'],
      ['Você', '[Elle] [a|avoir|tem] [trois] [ans|an|anos].', 'Ela tem três anos.'],
      ['Secretária', "[J'|je][ai|avoir|tenho] [une] [place] [à] [quinze] [heures|heure]. [Ça va] ?", 'Tenho um horário às quinze horas. Está bom?'],
      ['Você', '[Oui], [parfait]. [Merci] [beaucoup] !', 'Sim, perfeito. Muito obrigado!'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_avoir', name: 'avoir: ter', chapter: 8,
      intro: 'Ouça estes três pedaços da conversa.',
      examples: ['elle [a] trois ans', 'vous [avez] une place', "j'[ai] une place"],
      question: 'O que a, avez e ai têm em comum?',
      options: ['São formas de avoir, ter', 'São formas de être, ser', 'São preposições'],
      correct: 0,
      hint: 'Quase. Vous avez une place quer dizer vocês têm um horário.',
      reveal: 'Isso. São formas de avoir, ter: j’ai, elle a, vous avez. E a idade vem com avoir, como em português: elle a trois ans, ela tem três anos.',
      apply_question: 'O que quer dizer?',
      apply_hint: 'Quase. Avoir é ter.',
      apply: [
        { fr: 'Il a faim.', pt: 'Ele tem fome.', options: ['Ele tem fome.', 'Ele é fome.'], correct: 0 },
        { fr: "J'ai un rendez-vous.", pt: 'Tenho um horário marcado.', options: ['Sou um horário.', 'Tenho um horário marcado.'], correct: 1 },
      ],
      extra: 'Febre também vem com avoir: elle a de la fièvre, ela tem febre.',
    },
    frame: {
      title: 'Monte a sua resposta', intro: 'Troque a idade quantas vezes quiser. Cada frase toca sozinha.',
      template: 'elle a ___ ans.', pt: 'ela tem ___ anos.', slot: ['deux', 'trois', 'quatre', 'cinq', 'six'],
    },
  },
  {
    id: 'm23', chapter: 'ch6',
    title: 'Explicar os sintomas',
    can_do: 'explicar ao médico o que a criança sente',
    intro: 'No consultório, o pediatra examina a Léa e faz perguntas.',
    lines: [
      ['Pediatra', "[Bonjour], Léa. [Alors], [qu'est-ce que] [elle] [a|avoir|tem] ?", 'Oi, Léa. Então, o que ela tem?'],
      ['Você', '[Elle] [a|avoir|tem] [de] [la] [fièvre] [depuis] [hier], [et] [elle] [tousse|tousser|tosse].', 'Ela está com febre desde ontem, e está tossindo.'],
      ['Pediatra', '[Elle] [a|avoir|tem] [une] [allergie] ?', 'Ela tem alguma alergia?'],
      ['Você', "[Non]. [Mais] [elle] [n'|ne][a|avoir|tem] [pas] [d'|de][énergie].", 'Não. Mas ela está sem energia.'],
      ['Pediatra', "[C'|ce][est|être|é] [un] [petit] [rhume]. [Voilà] [l'|la][ordonnance] [pour] [la] [pharmacie].", 'É um resfriado. Aqui está a receita para a farmácia.'],
      ['Você', '[Merci], [docteur].', 'Obrigado, doutor.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_ia_ie', name: '-ia vira -ie', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'allerg[ie]', pt: 'alergia' }, { fr: 'énerg[ie]', pt: 'energia' }, { fr: 'pharmac[ie]', pt: 'farmácia' }],
      question: 'O que o -ie do francês é no português?',
      options: ['-ia', '-ão', '-ez'],
      correct: 0,
      hint: 'Quase. Diga alergia e compare com allergie.',
      reveal: 'Isso. Palavras em -ia terminam em -ie em francês, e o e do fim fica calado. Alergia, allergie; energia, énergie.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ia por -ie.',
      apply: [
        { fr: 'géographie', pt: 'geografia', options: ['géographie', 'geografia'], correct: 0 },
        { fr: 'économie', pt: 'economia', options: ['economia', 'économie'], correct: 1 },
      ],
      extra: 'Repare também no ph de pharmacie: soa f, como em farmácia.',
    },
    frame: {
      title: 'Monte a sua explicação', intro: 'Troque o dia quantas vezes quiser. Cada frase toca sozinha.',
      template: 'elle a de la fièvre depuis ___.', pt: 'ela está com febre desde ___.', slot: ['hier', 'lundi', 'mardi', 'mercredi', 'jeudi'],
    },
  },
  {
    id: 'm24', chapter: 'ch6',
    title: 'Na farmácia',
    can_do: 'pedir algo para dor na farmácia',
    intro: 'Você acordou com dor de cabeça e passa na farmácia antes do trabalho.',
    lines: [
      ['Farmacêutica', '[Bonjour], [je] [vous] [écoute|écouter|escuto].', 'Bom dia, pode falar.'],
      ['Você', "[Bonjour]. [J'|je][ai|avoir|tenho] [une] [douleur] [à] [la] [tête].", 'Bom dia. Estou com uma dor na cabeça.'],
      ['Farmacêutica', "[Depuis] [quand] ? [Avec] [la] [chaleur], [c'|ce][est|être|é] [normal].", 'Desde quando? Com o calor, é normal.'],
      ['Você', '[Depuis] [ce] [matin]. [Vous] [avez|avoir|tem] [quelque chose] [pour] [la] [douleur] ?', 'Desde hoje de manhã. Você tem alguma coisa para a dor?'],
      ['Farmacêutica', '[Du] [paracétamol]. [Si] [ça] [continue|continuer|continua], [allez|aller|vá] [chez] [le] [docteur].', 'Paracetamol. Se continuar, vá ao médico.'],
      ['Você', '[Merci] [beaucoup], [madame].', 'Muito obrigado, senhora.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_or_eur', name: '-or vira -eur', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'doul[eur]', pt: 'dor' }, { fr: 'chal[eur]', pt: 'calor' }, { fr: 'doct[eur]', pt: 'doutor' }],
      question: 'O que o -eur do francês é no português?',
      options: ['-or', '-ura', '-eiro'],
      correct: 0,
      hint: 'Quase. Diga doutor e compare com docteur.',
      reveal: 'Isso. Palavras em -or viram -eur, com o eu de biquinho: doutor, docteur; calor, chaleur; dor, douleur.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -or por -eur.',
      apply: [
        { fr: 'couleur', pt: 'cor', options: ['couleur', 'color'], correct: 0 },
        { fr: 'moteur', pt: 'motor', options: ['motor', 'moteur'], correct: 1 },
      ],
      extra: 'Profissões também: acteur, ator; directeur, diretor.',
    },
    frame: {
      title: 'Monte o seu pedido', intro: 'Troque o incômodo quantas vezes quiser. Cada frase toca sozinha.',
      template: 'vous avez quelque chose pour la ___ ?', pt: 'você tem alguma coisa para a ___?', slot: ['douleur', 'fièvre', 'toux', 'gorge', 'tête'],
    },
  },
  {
    id: 'm25', chapter: 'ch6',
    title: 'O remédio e o reembolso',
    can_do: 'perguntar sobre o reembolso e como tomar o remédio',
    intro: 'Na farmácia, com a receita da Léa na mão, você tem duas dúvidas.',
    lines: [
      ['Você', '[Ce] [médicament], [il] [est|être|é] [remboursé|rembourser|reembolsado] ?', 'Este remédio é reembolsado?'],
      ['Farmacêutica', "[Normalement], [oui]. [Vous] [avez|avoir|tem] [l'|la][ordonnance] ?", 'Normalmente, sim. Você tem a receita?'],
      ['Você', '[Oui], [voilà]. [Je] [paie|payer|pago] [directement] [ici] ?', 'Sim, aqui está. Eu pago direto aqui?'],
      ['Farmacêutica', '[Exactement]. [Après], [vous] [envoyez|envoyer|envia] [le] [reçu] [pour] [le] [remboursement].', 'Exatamente. Depois você envia o recibo para o reembolso.'],
      ['Você', "[Et] [le] [sirop], [c'|ce][est|être|é] [combien] [de] [fois] [par] [jour] ?", 'E o xarope, é quantas vezes por dia?'],
      ['Farmacêutica', "[Deux] [fois] [par] [jour], [simplement] [avec] [de] [l'|la][eau].", 'Duas vezes por dia, simplesmente com água.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_mente_ment', name: '-mente vira -ment', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'normale[ment]', pt: 'normalmente' }, { fr: 'directe[ment]', pt: 'diretamente' }, { fr: 'exacte[ment]', pt: 'exatamente' }],
      question: 'O que o -ment do francês é no português?',
      options: ['-mente', '-mento', '-ção'],
      correct: 0,
      hint: 'Quase. Diga exatamente e compare com exactement.',
      reveal: 'Isso. Os advérbios em -mente viram -ment, e o t do fim fica calado: normalmente, normalement; exatamente, exactement.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -mente por -ment.',
      apply: [
        { fr: 'rapidement', pt: 'rapidamente', options: ['rapidement', 'rapidamente'], correct: 0 },
        { fr: 'finalement', pt: 'finalmente', options: ['finalmente', 'finalement'], correct: 1 },
      ],
      extra: 'O -ment soa mã, como o en de rendez-vous.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o remédio quantas vezes quiser. Cada frase toca sozinha.',
      template: 'ce ___, il est remboursé ?', pt: 'este ___ é reembolsado?', slot: ['médicament', 'sirop', 'vaccin', 'contrôle'],
    },
  },

  // ===========================================================================
  // Capítulo 7 · Banco
  // ===========================================================================
  {
    id: 'm26', chapter: 'ch7',
    title: 'Abrir uma conta',
    can_do: 'pedir para abrir uma conta',
    intro: 'Você chega ao banco para abrir a primeira conta em Luxemburgo.',
    lines: [
      ['Você', "[Bonjour]. [Je] [voudrais|vouloir|queria] [ouvrir] [un] [compte]. [C'|ce][est|être|é] [possible] ?", 'Bom dia. Eu queria abrir uma conta. É possível?'],
      ['Bancária', '[Oui], [bien sûr]. [Vous] [êtes|être|está] [disponible] [maintenant] ?', 'Sim, claro. Você está disponível agora?'],
      ['Você', "[Oui]. [J'|je][ai|avoir|tenho] [mon] [passeport] [et] [mon] [contrat] [de] [travail].", 'Sim. Tenho meu passaporte e meu contrato de trabalho.'],
      ['Bancária', '[Parfait]. Marc, [le] [conseiller], [est|être|é] [responsable] [de] [votre] [dossier].', 'Perfeito. O Marc, o gerente, é responsável pelo seu processo.'],
      ['Você', '[Et] [la] [carte], [elle] [arrive|arriver|chega] [quand] ?', 'E o cartão, chega quando?'],
      ['Bancária', '[Dans] [une] [semaine], [à] [votre] [adresse].', 'Em uma semana, no seu endereço.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_vel_ble', name: '-vel vira -ble', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'possi[ble]', pt: 'possível' }, { fr: 'disponi[ble]', pt: 'disponível' }, { fr: 'responsa[ble]', pt: 'responsável' }],
      question: 'O que o -ble do francês é no português?',
      options: ['-vel', '-bo', '-ção'],
      correct: 0,
      hint: 'Quase. Diga possível e compare com possible.',
      reveal: 'Isso. Os adjetivos em -vel viram -ble: possível, possible; disponível, disponible; responsável, responsable.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -vel por -ble.',
      apply: [
        { fr: 'agréable', pt: 'agradável', options: ['agréable', 'agradável'], correct: 0 },
        { fr: 'impossible', pt: 'impossível', options: ['impossível', 'impossible'], correct: 1 },
      ],
      extra: 'O e do fim fica calado: possible soa possíbl.',
    },
    frame: {
      title: 'Monte a sua frase', intro: 'Troque o documento quantas vezes quiser. Cada frase toca sozinha.',
      template: "j'ai mon ___.", pt: 'tenho meu ___.', slot: ['passeport', 'contrat', 'certificat', 'document'],
    },
  },
  {
    id: 'm27', chapter: 'ch7',
    title: 'Pagar uma fatura',
    can_do: 'pagar uma fatura por transferência',
    intro: 'Chegou a fatura da creche. Você vai ao banco pagar por transferência.',
    lines: [
      ['Você', '[Je] [voudrais|vouloir|queria] [payer] [cette|ce|esta] [facture] [par] [virement].', 'Eu queria pagar esta fatura por transferência.'],
      ['Bancário', "[Oui]. [Le] [montant], [c'|ce][est|être|é] [quatre]-[vingts|vingt|vinte] [euros|euro] ?", 'Sim. O valor é oitenta euros?'],
      ['Você', '[Non], [soixante]-[quinze].', 'Não, setenta e cinco.'],
      ['Bancário', '[Soixante]-[quinze]… [et] [la] [référence] ?', 'Setenta e cinco… e a referência?'],
      ['Você', "[C'|ce][est|être|é] [quatre]-[vingt]-[dix]-[sept].", 'É noventa e sete.'],
      ['Bancário', "[Parfait]. [C'est fait|c'est fait].", 'Perfeito. Está feito.'],
    ],
    key: {
      kind: 'gramatica', ref: 'g_numeros', name: 'os números depois do 69', chapter: 13,
      intro: 'Ouça estes três números da conversa.',
      examples: ['[soixante]-[quinze]', '[quatre-vingts]', '[quatre-vingt]-[dix-sept]'],
      question: 'Como o francês diz 75?',
      options: ['Sessenta e quinze: soixante-quinze', 'Setenta e cinco: septante-cinq', 'Sete e cinco'],
      correct: 0,
      hint: 'Quase. Soixante é sessenta. Quanto falta para 75?',
      reveal: 'Isso. Depois do 69, o francês faz conta: 75 é sessenta e quinze, 80 é quatro vezes vinte, 97 é quatro vezes vinte mais dezessete. Em Luxemburgo se usa esse padrão da França.',
      apply_question: 'Qual é a conta?',
      apply_hint: 'Quase. Soixante é 60 e quatre-vingts é 4 × 20.',
      apply: [
        { fr: 'soixante-dix', pt: '70', options: ['60 + 10', '7 × 10'], correct: 0 },
        { fr: 'quatre-vingt-dix', pt: '90', options: ['4 + 20 + 10', '4 × 20 + 10'], correct: 1 },
      ],
      extra: 'Até 69, tudo segue o português: vingt et un, trente-deux, soixante-cinq.',
    },
    frame: {
      title: 'Monte o seu pedido', intro: 'Troque o que você vai pagar quantas vezes quiser. Cada frase toca sozinha.',
      template: 'je voudrais payer cette ___ par virement.', pt: 'eu queria pagar esta ___ por transferência.', slot: ['facture', 'amende', 'cotisation', 'commande'],
    },
  },
  {
    id: 'm28', chapter: 'ch7',
    title: 'Mostrar a identidade',
    can_do: 'mostrar seus documentos no banco',
    intro: 'Para liberar o cartão, a bancária pede um documento.',
    lines: [
      ['Bancária', "[Pour] [votre] [sécurité], [j'|je][ai|avoir|tenho] [besoin] [d'|de][une] [pièce d'identité].", 'Para a sua segurança, preciso de um documento de identidade.'],
      ['Você', "[Voilà] [ma] [carte] [d'|de][identité].", 'Aqui está a minha carteira de identidade.'],
      ['Bancária', "[Merci]. [La] [date] [de] [validité], [c'|ce][est|être|está] [bon].", 'Obrigada. A data de validade está boa.'],
      ['Bancária', '[Et] [votre] [nationalité] ?', 'E a sua nacionalidade?'],
      ['Você', "[J'|je][ai|avoir|tenho] [la] [nationalité] [brésilienne|brésilien|brasileira].", 'Tenho a nacionalidade brasileira.'],
      ['Bancária', '[Parfait]. [Votre] [carte] [bancaire] [arrive|arriver|chega] [dans] [une] [semaine].', 'Perfeito. Seu cartão do banco chega em uma semana.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_dade_te', name: '-dade vira -té', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'identi[té]', pt: 'identidade' }, { fr: 'validi[té]', pt: 'validade' }, { fr: 'nationali[té]', pt: 'nacionalidade' }],
      question: 'O que o -té do francês é no português?',
      options: ['-dade', '-tura', '-mente'],
      correct: 0,
      hint: 'Quase. Diga identidade e compare com identité.',
      reveal: 'Isso. As palavras em -dade viram -té, e são sempre femininas: identidade, identité; nacionalidade, nationalité.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -dade por -té.',
      apply: [
        { fr: 'université', pt: 'universidade', options: ['université', 'universidade'], correct: 0 },
        { fr: 'liberté', pt: 'liberdade', options: ['liberdade', 'liberté'], correct: 1 },
      ],
      extra: 'Todas femininas: la liberté, la nationalité, l’université.',
    },
    frame: {
      title: 'Monte a sua frase', intro: 'Troque o documento quantas vezes quiser. Cada frase toca sozinha.',
      template: 'voilà ma ___.', pt: 'aqui está a minha ___.', slot: ['carte', 'facture', 'attestation', 'copie'],
    },
  },
  {
    id: 'm29', chapter: 'ch7',
    title: 'Entender as taxas',
    can_do: 'perguntar sobre as taxas da conta',
    intro: 'No extrato aparecem valores que você não reconhece. Você pergunta no banco.',
    lines: [
      ['Você', '[Pardon], [je] [ne] [comprends|comprendre|entendo] [pas] [ces|ce|estas] [frais].', 'Desculpe, não entendo estas taxas.'],
      ['Bancário', '[Ce] [sont|être|são] [les] [frais] [annuels|annuel|anuais] [de] [la] [carte].', 'São as taxas anuais do cartão.'],
      ['Você', "[Et] [ce] [montant], [c'|ce][est|être|é] [mensuel] ?", 'E este valor, é mensal?'],
      ['Bancário', "[Oui], [c'|ce][est|être|é] [le] [prix] [du] [compte], [chaque|chaque|todo] [mois].", 'Sim, é o preço da conta, todo mês.'],
      ['Você', "[D'accord]. [Vous] [avez|avoir|tem] [un] [document] [officiel] ?", 'Combinado. Você tem um documento oficial?'],
      ['Bancário', '[Voilà] [le] [relevé] [officiel], [avec] [tout] [le] [détail].', 'Aqui está o extrato oficial, com todos os detalhes.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_al_el', name: '-al vira -el', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'annu[el]s', pt: 'anuais' }, { fr: 'mensu[el]', pt: 'mensal' }, { fr: 'offici[el]', pt: 'oficial' }],
      question: 'O que o -el do francês é no português?',
      options: ['-al', '-il', '-ol'],
      correct: 0,
      hint: 'Quase. Diga oficial e compare com officiel.',
      reveal: 'Isso. Muitos adjetivos em -al viram -el: mensal, mensuel; oficial, officiel; anual, annuel. Alguns ficam iguais, como normal.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -al por -el.',
      apply: [
        { fr: 'personnel', pt: 'pessoal', options: ['personnel', 'personal'], correct: 0 },
        { fr: 'naturel', pt: 'natural', options: ['natural', 'naturel'], correct: 1 },
      ],
      extra: 'Normal e final continuam iguais: são as exceções mais comuns.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque a palavra quantas vezes quiser. Cada frase toca sozinha.',
      template: "ce montant, c'est ___ ?", pt: 'este valor é ___?', slot: ['mensuel', 'annuel', 'normal', 'correct', 'officiel'],
    },
  },
  // ===========================================================================
  // Capítulo 8 · Vizinhança
  // ===========================================================================
  {
    id: 'm30', chapter: 'ch8',
    title: 'Uma vizinha nova',
    can_do: 'receber alguém novo no prédio',
    intro: 'Uma moça carrega caixas no corredor. É a vizinha nova do seu andar.',
    lines: [
      ['Você', '[Bonjour] ! [Vous] [êtes|être|é] [la] [nouvelle|nouveau|nova] [voisine] ?', 'Bom dia! Você é a vizinha nova?'],
      ['Vizinha', "[Oui] ! [Moi], [c'|ce][est|être|sou] Sophie. [Je] [suis|être|sou] [française|français|francesa]. [Et] [vous] ?", 'Sim! Eu sou a Sophie. Sou francesa. E vocês?'],
      ['Você', '[Nous] [sommes|être|somos] [brésiliens|brésilien|brasileiros]. [Vous] [parlez|parler|fala] [portugais] ?', 'Somos brasileiros. Você fala português?'],
      ['Vizinha', '[Non], [mais] [je] [parle|parler|falo] [anglais] [et] [un] [peu] [japonais].', 'Não, mas falo inglês e um pouco de japonês.'],
      ['Você', "[Super] ! [Bienvenue] [dans] [l'|le][immeuble].", 'Que ótimo! Bem-vinda ao prédio.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_es_ais', name: '-ês vira -ais', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'portug[ais]', pt: 'português' }, { fr: 'angl[ais]', pt: 'inglês' }, { fr: 'japon[ais]', pt: 'japonês' }],
      question: 'O que o -ais do francês é no português?',
      options: ['-ês', '-ão', '-ano'],
      correct: 0,
      hint: 'Quase. Diga japonês e compare com japonais.',
      reveal: 'Isso. Línguas e nacionalidades em -ês terminam em -ais, que soa é: português, portugais; inglês, anglais. No feminino, -aise: française.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ês por -ais.',
      apply: [
        { fr: 'hollandais', pt: 'holandês', options: ['hollandais', 'holandês'], correct: 0 },
        { fr: 'chinois', pt: 'chinês', options: ['chinais', 'chinois'], correct: 1 },
      ],
      extra: 'Nem todas seguem: chinês é chinois. Mas a maioria segue, e o ai sempre soa é.',
    },
    frame: {
      title: 'Monte a sua frase', intro: 'Troque a língua quantas vezes quiser. Cada frase toca sozinha.',
      template: 'je parle anglais et un peu ___.', pt: 'falo inglês e um pouco de ___.', slot: ['japonais', 'portugais', 'français', 'allemand', 'luxembourgeois'],
    },
  },
  {
    id: 'm31', chapter: 'ch8',
    title: 'O lixo e a reciclagem',
    can_do: 'perguntar onde vai cada tipo de lixo',
    intro: 'Primeira semana no prédio. Você não sabe onde deixar as embalagens e pergunta a uma vizinha.',
    lines: [
      ['Você', "[Pardon], [madame]. [Où] [est-ce que] [je] [mets|mettre|coloco] [les] [emballages|emballage|embalagens] ?", 'Desculpe, senhora. Onde eu coloco as embalagens?'],
      ['Vizinha', '[Dans] [la] [poubelle] [du] [recyclage], [au] [garage].', 'Na lixeira da reciclagem, na garagem.'],
      ['Você', '[Et] [le] [verre] ?', 'E o vidro?'],
      ['Vizinha', "[Le] [verre], [c'|ce][est|être|vai] [dans] [le] [conteneur], [dans] [la] [rue].", 'O vidro vai no contêiner, na rua.'],
      ['Você', '[Et] [le] [papier] ?', 'E o papel?'],
      ['Vizinha', '[Le] [papier] [aussi], [au] [garage].', 'O papel também, na garagem.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_agem_age', name: '-agem vira -age', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'emball[age]s', pt: 'embalagens' }, { fr: 'recycl[age]', pt: 'reciclagem' }, { fr: 'gar[age]', pt: 'garagem' }],
      question: 'O que o -age do francês é no português?',
      options: ['-agem', '-ável', '-ança'],
      correct: 0,
      hint: 'Quase. Diga garagem e compare com garage.',
      reveal: 'Isso. As palavras em -agem terminam em -age, que soa aj: garagem, garage; reciclagem, recyclage. E são masculinas: le garage.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -agem por -age.',
      apply: [
        { fr: 'voyage', pt: 'viagem', options: ['voyage', 'viagem'], correct: 0 },
        { fr: 'message', pt: 'mensagem', options: ['mensagem', 'message'], correct: 1 },
      ],
      extra: 'Repare no gênero: a garagem, mas le garage. As palavras em -age costumam ser masculinas.',
    },
    frame: {
      title: 'Monte a sua pergunta', intro: 'Troque o tipo de lixo quantas vezes quiser. Cada frase toca sozinha.',
      template: 'et le ___ ?', pt: 'e o ___?', slot: ['verre', 'papier', 'plastique', 'carton'],
    },
  },
  {
    id: 'm32', chapter: 'ch8', pronoun: 'Ele',
    title: 'Barulho à noite',
    can_do: 'pedir menos barulho com educação',
    intro: 'Dez da noite, e o apartamento de cima está cheio de gente. Você sobe e toca a campainha.',
    lines: [
      ['Você', '[Bonsoir]. [Pardon], [il y a] [beaucoup] [de] [bruit] [ce] [soir].', 'Boa noite. Desculpe, tem muito barulho hoje à noite.'],
      ['Vizinho', "[Pardon] ! [C'|ce][est|être|é] [une] [réunion] [de] [famille] [dans] [le] [salon].", 'Desculpe! É uma reunião de família na sala.'],
      ['Você', '[Je] [comprends|comprendre|entendo]. [Mais] [les] [enfants|enfant|crianças] [dorment|dormir|dormem].', 'Eu entendo. Mas as crianças estão dormindo.'],
      ['Vizinho', '[Vous] [avez|avoir|tem] [raison]. [On] [va|aller|vai] [faire] [attention].', 'Você tem razão. A gente vai tomar cuidado.'],
      ['Você', '[Merci] [beaucoup]. [Bonne] [soirée] !', 'Muito obrigado. Boa noite!'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_ao_on', name: '-ão vira -on', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'réuni[on]', pt: 'reunião' }, { fr: 'sal[on]', pt: 'salão' }, { fr: 'rais[on]', pt: 'razão' }],
      question: 'O que o -on do francês é no português?',
      options: ['-ão', '-om', '-ona'],
      correct: 0,
      hint: 'Quase. Diga reunião e compare com réunion.',
      reveal: 'Isso. Muitas palavras em -ão terminam em -on, que soa õ: reunião, réunion; razão, raison; salão, salon.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ão por -on.',
      apply: [
        { fr: 'avion', pt: 'avião', options: ['avion', 'avião'], correct: 0 },
        { fr: 'ballon', pt: 'balão, bola', options: ['balão', 'ballon'], correct: 1 },
      ],
      extra: 'O on soa õ, a nasal que você viu no guichê da Commune.',
    },
    frame: {
      title: 'Monte o seu pedido', intro: 'Troque o que incomoda quantas vezes quiser. Cada frase toca sozinha.',
      template: 'il y a beaucoup de ___ ce soir.', pt: 'tem muito ___ hoje à noite.', slot: ['bruit', 'monde', 'musique', 'vent'],
    },
  },
  {
    id: 'm33', chapter: 'ch8',
    title: 'Pedir um favor',
    can_do: 'pedir um favor a um vizinho',
    intro: 'Vocês vão viajar uma semana e precisam de alguém para ficar com a chave.',
    lines: [
      ['Você', '[Bonjour] ! [Je] [peux|pouvoir|posso] [vous] [demander] [un] [service] ?', 'Bom dia! Posso lhe pedir um favor?'],
      ['Vizinha', "[Bien sûr]. [Qu'est-ce que] [c'|ce][est|être|é] ?", 'Claro. O que é?'],
      ['Você', '[Nous] [partons|partir|vamos viajar] [une] [semaine]. [Vous] [pouvez|pouvoir|pode] [garder] [la] [clé] ?', 'Vamos viajar por uma semana. Você pode guardar a chave?'],
      ['Vizinha', '[Oui], [avec] [plaisir]. [Je] [peux|pouvoir|posso] [passer] [pour] [les] [plantes|plante|plantas].', 'Sim, com prazer. Posso passar para ver as plantas.'],
      ['Você', "[Merci] ! [Et] [vous] [pouvez|pouvoir|pode] [contrôler] [le] [courrier] ?", 'Obrigado! E pode conferir a correspondência?'],
      ['Vizinha', '[Pas de problème]. [Bon voyage] !', 'Sem problema. Boa viagem!'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_ar_er', name: 'verbos -ar viram -er', chapter: 1,
      intro: 'Ouça estes três verbos da conversa e pense no português.',
      examples: [{ fr: 'gard[er]', pt: 'guardar' }, { fr: 'pass[er]', pt: 'passar' }, { fr: 'contrôl[er]', pt: 'controlar' }],
      question: 'O que o -er desses verbos é no português?',
      options: ['-ar', '-er', '-ir'],
      correct: 0,
      hint: 'Quase. Diga passar e compare com passer.',
      reveal: 'Isso. Muitos verbos em -ar têm o infinitivo em -er, que soa ê: passar, passer; guardar, garder; controlar, contrôler.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ar por -er.',
      apply: [
        { fr: 'signer', pt: 'assinar', options: ['signer', 'signar'], correct: 0 },
        { fr: 'continuer', pt: 'continuar', options: ['continuar', 'continuer'], correct: 1 },
      ],
      extra: 'O r do fim fica calado: passer soa passê.',
    },
    frame: {
      title: 'Monte o seu pedido', intro: 'Troque o verbo quantas vezes quiser. Cada frase toca sozinha.',
      template: 'vous pouvez ___ la clé ?', pt: 'você pode ___ a chave?', slot: ['garder', 'prendre', 'chercher', 'donner'],
    },
  },

  // ===========================================================================
  // Capítulo 9 · Entrevista de emprego
  // ===========================================================================
  {
    id: 'm34', chapter: 'ch9',
    title: 'Se apresentar na entrevista',
    can_do: 'falar da sua experiência numa entrevista',
    intro: 'Primeira entrevista de emprego em Luxemburgo. A recrutadora convida você a sentar.',
    lines: [
      ['Recrutadora', '[Bonjour], [asseyez-vous]. [Parlez|parler|fale]-[moi] [de] [votre] [expérience].', 'Bom dia, sente-se. Fale da sua experiência.'],
      ['Você', "[J'|je][ai|avoir|tenho] [cinq] [ans|an|anos] [d'|de][expérience] [en] [informatique].", 'Tenho cinco anos de experiência em informática.'],
      ['Recrutadora', '[Très] [bien]. [Et] [vos|votre|suas] [compétences|compétence|competências] ?', 'Muito bem. E as suas competências?'],
      ['Você', "[Je] [parle|parler|falo] [trois] [langues|langue|línguas], [et] [j'|je][ai|avoir|tenho] [de] [la] [patience] [avec] [les] [clients|client|clientes].", 'Falo três línguas e tenho paciência com os clientes.'],
      ['Recrutadora', "[La] [patience], [c'|ce][est|être|é] [important] [ici]. [Et] [le] [français] ?", 'A paciência é importante aqui. E o francês?'],
      ['Você', "[J'|je][apprends|apprendre|aprendo], [un] [peu] [chaque] [jour].", 'Estou aprendendo, um pouco a cada dia.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_ancia_ance', name: '-ência vira -ence', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'expéri[ence]', pt: 'experiência' }, { fr: 'compét[ence]s', pt: 'competências' }, { fr: 'pati[ence]', pt: 'paciência' }],
      question: 'O que o -ence do francês é no português?',
      options: ['-ência', '-ente', '-ença'],
      correct: 0,
      hint: 'Quase. Diga paciência e compare com patience.',
      reveal: 'Isso. As palavras em -ência e -ância viram -ence e -ance, que soam ãs: experiência, expérience; paciência, patience; importância, importance.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ência por -ence.',
      apply: [
        { fr: 'urgence', pt: 'urgência', options: ['urgence', 'urgência'], correct: 0 },
        { fr: 'distance', pt: 'distância', options: ['distância', 'distance'], correct: 1 },
      ],
      extra: 'O en e o an de -ence e -ance soam ã, nasal: patience soa paciãs.',
    },
    frame: {
      title: 'Monte a sua frase', intro: 'Troque a área quantas vezes quiser. Cada frase toca sozinha.',
      template: "j'ai cinq ans d'expérience en ___.", pt: 'tenho cinco anos de experiência em ___.', slot: ['informatique', 'économie', 'droit', 'comptabilité'],
    },
  },
  {
    id: 'm35', chapter: 'ch9',
    title: 'O que você fazia antes',
    can_do: 'dizer qual era o seu trabalho',
    intro: 'A recrutadora quer saber do seu trabalho no Brasil.',
    lines: [
      ['Recrutadora', '[Au] Brésil, [vous] [avez|avoir] [travaillé|travailler|trabalhou] [où] ?', 'No Brasil, onde você trabalhou?'],
      ['Você', "[J'|je][ai|avoir] [travaillé|travailler|trabalhei] [comme] [journaliste], [puis] [comme] [spécialiste] [en] [communication].", 'Trabalhei como jornalista, depois como especialista em comunicação.'],
      ['Recrutadora', "[Journaliste] ? [C'|ce][est|être|é] [intéressant]. [Et] [ici] ?", 'Jornalista? Que interessante. E aqui?'],
      ['Você', '[Ici], [je] [cherche|chercher|procuro] [un] [poste] [de] [spécialiste].', 'Aqui, procuro uma vaga de especialista.'],
      ['Recrutadora', "[Nous] [avons|avoir|temos] [justement] [besoin] [d'|de][un] [spécialiste].", 'Justamente precisamos de um especialista.'],
      ['Você', '[Parfait] ! [Je] [suis|être|sou] [très] [optimiste].', 'Perfeito! Estou muito otimista.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_ista_iste', name: '-ista vira -iste', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'journal[iste]', pt: 'jornalista' }, { fr: 'spécial[iste]', pt: 'especialista' }, { fr: 'optim[iste]', pt: 'otimista' }],
      question: 'O que o -iste do francês é no português?',
      options: ['-ista', '-ismo', '-este'],
      correct: 0,
      hint: 'Quase. Diga jornalista e compare com journaliste.',
      reveal: 'Isso. Profissões e jeitos de ser em -ista terminam em -iste, com o e calado: jornalista, journaliste; otimista, optimiste.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ista por -iste.',
      apply: [
        { fr: 'dentiste', pt: 'dentista', options: ['dentiste', 'dentista'], correct: 0 },
        { fr: 'artiste', pt: 'artista', options: ['artista', 'artiste'], correct: 1 },
      ],
      extra: 'Servem para homem e mulher: un journaliste, une journaliste.',
    },
    frame: {
      title: 'Monte a sua frase', intro: 'Troque a vaga quantas vezes quiser. Cada frase toca sozinha.',
      template: 'je cherche un poste de ___.', pt: 'procuro uma vaga de ___.', slot: ['spécialiste', 'journaliste', 'développeur', 'comptable', 'vendeur'],
    },
  },
  {
    id: 'm36', chapter: 'ch9',
    title: 'Seus pontos fortes',
    can_do: 'dizer como você trabalha',
    intro: 'Perto do fim da entrevista, vem a pergunta sobre você.',
    lines: [
      ['Recrutadora', '[Vos|votre|seus] [collègues|collègue|colegas] [disent|dire|dizem] [quoi] [de] [vous] ?', 'O que os seus colegas dizem de você?'],
      ['Você', "[Que] [je] [suis|être|sou] [une] [personne] [créative|créatif|criativa] [et] [active|actif|ativa].", 'Que sou uma pessoa criativa e ativa.'],
      ['Recrutadora', "[Et] [vous] [êtes|être|é] [quelqu'un] [de] [positif] ?", 'E você é alguém positivo?'],
      ['Você', "[Oui], [très] [positif]. [J'|je][aime|aimer|gosto de] [travailler] [en] [équipe].", 'Sim, muito positivo. Gosto de trabalhar em equipe.'],
      ['Recrutadora', '[Parfait]. [Vous] [êtes|être|está] [disponible] [pour] [un] [deuxième] [entretien] ?', 'Perfeito. Você está disponível para uma segunda entrevista?'],
      ['Você', '[Oui], [bien sûr].', 'Sim, claro.'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_ivo_if', name: '-ivo vira -if', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'créat[ive]', pt: 'criativa' }, { fr: 'act[ive]', pt: 'ativa' }, { fr: 'posit[if]', pt: 'positivo' }],
      question: 'O que o -if e o -ive do francês são no português?',
      options: ['-ivo e -iva', '-ável', '-ência'],
      correct: 0,
      hint: 'Quase. Diga positivo e compare com positif.',
      reveal: 'Isso. Os adjetivos em -ivo terminam em -if, e no feminino em -ive: positivo, positif; criativa, créative; ativa, active.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -ivo por -if.',
      apply: [
        { fr: 'sportif', pt: 'esportivo', options: ['sportif', 'sportivo'], correct: 0 },
        { fr: 'négatif', pt: 'negativo', options: ['negativo', 'négatif'], correct: 1 },
      ],
      extra: 'O f do fim aparece no som, como em careful: positif soa pozitíf.',
    },
    frame: {
      title: 'Monte a sua resposta', intro: 'Troque o convite quantas vezes quiser. Cada frase toca sozinha.',
      template: 'vous êtes disponible pour un deuxième ___ ?', pt: 'você está disponível para um(a) segundo(a) ___?', slot: ['entretien', 'rendez-vous', 'café', 'stage'],
    },
  },
  {
    id: 'm37', chapter: 'ch9',
    title: 'Combinar o início',
    can_do: 'combinar quando você começa a trabalhar',
    intro: 'A vaga é sua. Falta combinar a data de início.',
    lines: [
      ['Recrutadora', '[Vous] [pouvez|pouvoir|pode] [commencer] [quand] ?', 'Quando você pode começar?'],
      ['Você', "[Le] [premier] [janvier], [c'|ce][est|être|é] [possible] ?", 'Primeiro de janeiro, é possível?'],
      ['Recrutadora', '[Plutôt] [le] [premier] [février]. [Le] [contrat] [arrive|arriver|chega] [en] [janvier].', 'Melhor primeiro de fevereiro. O contrato chega em janeiro.'],
      ['Você', "[D'accord]. [Février], [c'|ce][est|être|é] [parfait].", 'Combinado. Fevereiro está perfeito.'],
      ['Recrutadora', "[Bienvenue] [dans] [l'|la][équipe] !", 'Bem-vindo à equipe!'],
      ['Você', '[Merci] [beaucoup]. [À bientôt] !', 'Muito obrigado. Até logo!'],
    ],
    key: {
      kind: 'ponte', ref: 'cr_eiro_ier', name: '-eiro vira -ier', chapter: 1,
      intro: 'Ouça estas três palavras da conversa e pense no português.',
      examples: [{ fr: 'prem[ier]', pt: 'primeiro' }, { fr: 'janv[ier]', pt: 'janeiro' }, { fr: 'févr[ier]', pt: 'fevereiro' }],
      question: 'O que o -ier do francês é no português?',
      options: ['-eiro', '-ário', '-ível'],
      correct: 0,
      hint: 'Quase. Diga janeiro e compare com janvier.',
      reveal: 'Isso. Palavras em -eiro terminam em -ier, que soa iê: primeiro, premier; janeiro, janvier; fevereiro, février.',
      apply_question: 'Como é em francês?',
      apply_hint: 'Quase. Troque o -eiro por -ier.',
      apply: [
        { fr: 'cuisinier', pt: 'cozinheiro', options: ['cuisinier', 'cuisineiro'], correct: 0 },
        { fr: 'infirmier', pt: 'enfermeiro', options: ['enfermeiro', 'infirmier'], correct: 1 },
      ],
      extra: 'Você chegou ao fim da trilha. Tudo o que viu continua voltando nos reencontros.',
    },
    frame: {
      title: 'Monte a sua proposta', intro: 'Troque o mês quantas vezes quiser. Cada frase toca sozinha.',
      template: "le premier ___, c'est possible ?", pt: 'primeiro de ___, é possível?', slot: ['janvier', 'février', 'mars', 'avril', 'mai'],
    },
  },
];
