import { chromium, devices } from '@playwright/test';
const OUT = process.env.OUT;
const scheme = process.env.SCHEME || 'light';
const browser = await chromium.launch({ args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
const ctx = await browser.newContext({ ...devices['Pixel 7'], colorScheme: scheme, permissions: ['microphone'] });
const page = await ctx.newPage();
await page.addInitScript(() => {
  const list = [{ name: 'Amélie', lang: 'fr-FR' }, { name: 'Thomas', lang: 'fr-FR' }].map((v) => ({ ...v, voiceURI: v.name, localService: true, default: false }));
  speechSynthesis.getVoices = () => list;
  window.SpeechSynthesisUtterance = class { constructor(t) { this.text = t; } };
  speechSynthesis.speak = (u) => setTimeout(() => u.onend?.(), 10);
  speechSynthesis.cancel = () => {};
});
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
const shot = (n) => page.screenshot({ path: `${OUT}/${scheme}-${n}.png`, fullPage: true });
await page.goto((process.env.BASE ?? 'http://localhost:4174') + '/');
await page.click('[data-user="u_lucas"]');
await page.waitForSelector('[data-testid=hero]');
await shot('01-hoje-antes');
await page.click('[data-testid=start]');
await page.waitForSelector('[data-testid=step-listen]');
await page.click('[data-testid=toggle-pt]');
await page.screenshot({ path: `${OUT}/${scheme}-02-escute.png` });
await page.click('[data-testid=momento-next]');
await page.click('[data-testid=reveal-known]');
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/${scheme}-03-voce-ja-sabe.png` });
await page.locator('.tok', { hasText: 'lait' }).first().click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/${scheme}-03b-folha.png` });
await page.click('[data-testid=sheet-close]');
await page.click('[data-testid=momento-next]');
await page.locator('.opt').first().click();
await page.screenshot({ path: `${OUT}/${scheme}-04a-chave-quase.png` });
await page.locator('.opt[data-right="true"]').first().click();
for (const card of await page.locator('[data-testid=apply]').all()) await card.locator('.opt[data-right="true"]').click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/${scheme}-04-chave.png`, fullPage: false });
await page.click('[data-testid=key-more]');
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/${scheme}-04c-entender.png` });
await page.click('[data-testid=sheet-close]');
await page.click('[data-testid=momento-next]');
await page.locator('.chip', { hasText: 'chocolat chaud' }).click();
await page.screenshot({ path: `${OUT}/${scheme}-05-monte.png` });
await page.click('[data-testid=momento-next]');
await page.click('[data-testid=rec-start]');
await page.waitForTimeout(2500);
await page.click('[data-testid=rec-stop]');
await page.waitForTimeout(2000);
await page.screenshot({ path: `${OUT}/${scheme}-06-fale.png`, fullPage: false });
await page.click('[data-testid=momento-next]');
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/${scheme}-07-leve.png` });
await page.click('[data-testid=momento-next]');
await page.waitForTimeout(1800);
await shot('08-hoje-depois');
await page.goto((process.env.BASE ?? 'http://localhost:4174') + '/#/caderno');
await page.waitForTimeout(500);
await shot('09-caderno');
await page.goto((process.env.BASE ?? 'http://localhost:4174') + '/#/como-funciona');
await page.waitForTimeout(300);
await shot('10-como-funciona');
await page.goto((process.env.BASE ?? 'http://localhost:4174') + '/#/como-funciona/2');
await page.waitForTimeout(300);
await shot('11-capitulo-2');
await page.goto((process.env.BASE ?? 'http://localhost:4174') + '/#/ajustes');
await page.waitForTimeout(500);
await shot('12-ajustes');
console.log('errors', JSON.stringify(errors));
await browser.close();
